SPIKE 1.1: at86.h File Reference
at86.h File Reference
This file implements the API for the AT86RF231 radio transceiver.
#include <stdint.h>
#include <stdbool.h>
#include "at86rf231.h"
#include "tal_constants.h"
#include "ieee_const.h"
#include "pal_config.h"
#include <avr/io.h>
#include <inttypes.h>
#include <avr/Interrupt.h>
#include <util/delay.h>
Data Structures
struct at86rf231_frame
AT86RF231 Frame struct including frame header.
struct spike_payload
Spike tx payload data struct.
Macros
#define ENABLE_TRX_SRAM
#define PAL_RST_HIGH() RST_HIGH()
#define PAL_RST_LOW() RST_LOW()
#define PAL_SLP_TR_HIGH() SLP_TR_HIGH()
#define PAL_SLP_TR_LOW() SLP_TR_LOW()
#define READ_ACCESS_COMMAND (0x80)
#define RF_BAND BAND_2400
#define SAMPLES_PER_PACKET 7
#define SHORTENUM __attribute__((packed))
#define TAL_TYPE AT86RF231
#define TRX_CMD_FR (0x20)
#define TRX_CMD_FW (0x60)
#define TRX_CMD_SR (0x00)
#define TRX_CMD_SW (0x40)
#define WRITE_ACCESS_COMMAND (0xC0)
Typedefs
typedef enum csma_mode_tag csma_mode_t
typedef void(* irq_handler_t)(void)
typedef enum tal_state_tag tal_state_t
AT86RF231 Transceiver states.
typedef enum trx_irq_hdlr_idx_tag trx_irq_hdlr_idx_t
Enumerations
enum csma_mode_tag { NO_CSMA_NO_IFS, NO_CSMA_WITH_IFS, CSMA_UNSLOTTED, CSMA_SLOTTED }
enum tal_state_tag { TAL_IDLE = 0, TAL_TX_AUTO = 1, TAL_TX_DONE = 2 }
AT86RF231 Transceiver states.
enum trx_irq_hdlr_idx_tag {
TRX_MAIN_IRQ_HDLR_IDX = 0, TRX_TSTAMP_IRQ_HDLR_IDX, TRX_ALTERNATE_0_IRQ_HDLR_IDX, TRX_ALTERNATE_1_IRQ_HDLR_IDX,
TRX_ALTERNATE_2_IRQ_HDLR_IDX, TRX_ALTERNATE_3_IRQ_HDLR_IDX, TRX_ALTERNATE_4_IRQ_HDLR_IDX, TRX_ALTERNATE_5_IRQ_HDLR_IDX,
TRX_ALTERNATE_6_IRQ_HDLR_IDX, TRX_ALTERNATE_7_IRQ_HDLR_IDX
}
Functions
uint8_t at86rf231_change_channel (uint8_t new_channel)
Apply channel to transceiver.
bool at86rf231_change_channel_page (uint8_t ch_page)
Apply channel page configuartion to transceiver.
uint8_t at86rf231_change_tx_pwr (uint8_t pwr)
Apply tx power to transceiver.
void at86rf231_ftn_pll_calibration (void)
Filter tuning and PLL calibration handling Although receiver and transmitter are very robust against these variations, it is recommended to initiate the FTN manually if the radio transceiver does not use the SLEEP state. If necessary, a calibration cycle is to be initiated in states TRX_OFF, PLL_ON or any receive state. This applies in particular for the High Data Rate Modes with a much higher sensitivity against BPF transfer function variations. The recommended calibration interval is 5 min or less.
void at86rf231_init (void)
Init AT86RF231 Transceiver.
void at86rf231_req_data (void)
Send data request and receive data with ACK and retry.
void at86rf231_rx_with_auto_ack (void)
Set Transceiver State = RX_AACK_ON send ACK-Frame automatically if requested.
void at86rf231_sleep (void)
Set Transceiver mode = sleep.
uint8_t at86rf231_switch_pll_on (void)
Switch transceiver pll on and wait until it is locked.
void at86rf231_tx (void)
Send data without ACK and Retry.
void at86rf231_tx_with_retry (csma_mode_t csma_mode, bool tx_retries)
Sends frame.
void delay_us (uint16_t usec)
void handle_received_frame_irq (void)
Handle received frame interrupt.
static void pal_global_irq_disable (void)
Disables the global interrupt.
static void pal_global_irq_enable (void)
Enables the global interrupt.
uint8_t pal_trx_bit_read (uint8_t addr, uint8_t mask, uint8_t pos)
read specified bit from transceiver
void pal_trx_bit_write (uint8_t reg_addr, uint8_t mask, uint8_t pos, uint8_t new_value)
write specified bit to transceiver
void pal_trx_frame_read (uint8_t *data, uint8_t length)
Upload frame from transceiver.
void pal_trx_frame_write (uint8_t *data, uint8_t length)
write frame to transceiver
static void pal_trx_irq_disable (trx_irq_hdlr_idx_t trx_irq_num)
Disables the transceiver interrupt.
static void pal_trx_irq_enable (trx_irq_hdlr_idx_t trx_irq_num)
Enables the transceiver interrupt.
static void pal_trx_irq_flag_clr (trx_irq_hdlr_idx_t trx_irq_num)
Clears the transceiver interrupt.
void pal_trx_irq_init (trx_irq_hdlr_idx_t trx_irq_num, void *trx_irq_cb)
init external interrupt
uint8_t pal_trx_reg_read (uint8_t addr)
read register from transceiver
void pal_trx_reg_write (uint8_t addr, uint8_t data)
write register to transceiver
void trx_interface_init (void)
init spi interace
void trx_irq_handler_cb (void)
Transceiver interrupt handler.
Detailed Description
This file implements the API for the AT86RF231 radio transceiver.
Definition in file at86.h.
Macro Definition Documentation
#define ENABLE_TRX_SRAM
Definition at line 14 of file at86.h.
#define PAL_RST_HIGH () RST_HIGH()
Definition at line 106 of file at86.h.
Referenced by at86rf231_init().
#define PAL_RST_LOW () RST_LOW()
Definition at line 111 of file at86.h.
Referenced by at86rf231_init().
#define PAL_SLP_TR_HIGH () SLP_TR_HIGH()
Definition at line 116 of file at86.h.
Referenced by at86rf231_sleep(), at86rf231_tx(), and at86rf231_tx_with_retry().
#define PAL_SLP_TR_LOW () SLP_TR_LOW()
Definition at line 121 of file at86.h.
Referenced by at86rf231_init(), at86rf231_tx(), and at86rf231_tx_with_retry().
#define READ_ACCESS_COMMAND (0x80)
Definition at line 131 of file at86.h.
Referenced by pal_trx_reg_read().
#define RF_BAND BAND_2400
Definition at line 13 of file at86.h.
#define SAMPLES_PER_PACKET 7
Definition at line 28 of file at86.h.
Referenced by main().
#define SHORTENUM __attribute__((packed))
Definition at line 10 of file at86.h.
#define TAL_TYPE AT86RF231
Definition at line 9 of file at86.h.
#define TRX_CMD_FR (0x20)
Definition at line 141 of file at86.h.
Referenced by pal_trx_frame_read().
#define TRX_CMD_FW (0x60)
Definition at line 136 of file at86.h.
Referenced by pal_trx_frame_write().
#define TRX_CMD_SR (0x00)
Definition at line 151 of file at86.h.
Referenced by pal_trx_sram_read().
#define TRX_CMD_SW (0x40)
Definition at line 146 of file at86.h.
Referenced by pal_trx_aes_wrrd(), and pal_trx_sram_write().
#define WRITE_ACCESS_COMMAND (0xC0)
Definition at line 126 of file at86.h.
Referenced by pal_trx_reg_write().
Typedef Documentation
typedef enum csma_mode_tag csma_mode_t
Transceiver csma_mode_tag
typedef void(* irq_handler_t)(void)
This is a typedef of the function which is called from the transceiver ISR
Definition at line 99 of file at86.h.
typedef enum tal_state_tag tal_state_t
AT86RF231 Transceiver states.
typedef enum trx_irq_hdlr_idx_tag trx_irq_hdlr_idx_t
Transceiver interrupt handler index
Enumeration Type Documentation
enum csma_mode_tag
Transceiver csma_mode_tag
Enumerator
NO_CSMA_NO_IFS
NO_CSMA_WITH_IFS
CSMA_UNSLOTTED
CSMA_SLOTTED
Definition at line 88 of file at86.h.
 {
     NO_CSMA_NO_IFS,
     NO_CSMA_WITH_IFS,
     CSMA_UNSLOTTED,
     CSMA_SLOTTED
 } csma_mode_t;
enum tal_state_tag
AT86RF231 Transceiver states.
Enumerator
TAL_IDLE
TAL_TX_AUTO
TAL_TX_DONE
Definition at line 61 of file at86.h.
 {
     TAL_IDLE           = 0,
     TAL_TX_AUTO        = 1,
     TAL_TX_DONE        = 2
 } SHORTENUM tal_state_t;
enum trx_irq_hdlr_idx_tag
Transceiver interrupt handler index
Enumerator
TRX_MAIN_IRQ_HDLR_IDX
TRX_TSTAMP_IRQ_HDLR_IDX
TRX_ALTERNATE_0_IRQ_HDLR_IDX
TRX_ALTERNATE_1_IRQ_HDLR_IDX
TRX_ALTERNATE_2_IRQ_HDLR_IDX
TRX_ALTERNATE_3_IRQ_HDLR_IDX
TRX_ALTERNATE_4_IRQ_HDLR_IDX
TRX_ALTERNATE_5_IRQ_HDLR_IDX
TRX_ALTERNATE_6_IRQ_HDLR_IDX
TRX_ALTERNATE_7_IRQ_HDLR_IDX
Definition at line 71 of file at86.h.
 {
     TRX_MAIN_IRQ_HDLR_IDX = 0,
     TRX_TSTAMP_IRQ_HDLR_IDX,
     TRX_ALTERNATE_0_IRQ_HDLR_IDX, /* Spare IRQ for devices with multiple irqs */
     TRX_ALTERNATE_1_IRQ_HDLR_IDX, /* Spare IRQ for devices with multiple irqs */
     TRX_ALTERNATE_2_IRQ_HDLR_IDX, /* Spare IRQ for devices with multiple irqs */
     TRX_ALTERNATE_3_IRQ_HDLR_IDX, /* Spare IRQ for devices with multiple irqs */
     TRX_ALTERNATE_4_IRQ_HDLR_IDX, /* Spare IRQ for devices with multiple irqs */
     TRX_ALTERNATE_5_IRQ_HDLR_IDX, /* Spare IRQ for devices with multiple irqs */
     TRX_ALTERNATE_6_IRQ_HDLR_IDX, /* Spare IRQ for devices with multiple irqs */
     TRX_ALTERNATE_7_IRQ_HDLR_IDX  /* Spare IRQ for devices with multiple irqs */
 } trx_irq_hdlr_idx_t;
Function Documentation
uint8_t at86rf231_change_channel (uint8_t new_channel)
Apply channel to transceiver.
change transceiver channel
Parameters
uint8_t new_channel
Returns
content of channel register
Definition at line 369 of file at86rf231.c.
References CMD_TRX_OFF, pal_trx_bit_read(), pal_trx_bit_write(), pal_trx_reg_write(), RG_TRX_STATE, SR_CHANNEL, SR_TRX_STATUS, TRX_OFF, and TRX_SUPPORTED_CHANNELS.
Referenced by pm_config_protocol().
 {
     /* TRX status variale */
     tal_trx_status_t tal_trx_status = 0;
     if ((uint32_t)TRX_SUPPORTED_CHANNELS & ((uint32_t)0x01 << new_channel ))
     {
         /* Set Transceiver State = TRX_OFF */
         pal_trx_reg_write( RG_TRX_STATE, CMD_TRX_OFF );
         /* verify that state = TRX_OFF */
         while( tal_trx_status != TRX_OFF )
         {
             tal_trx_status = ( tal_trx_status_t )pal_trx_bit_read( SR_TRX_STATUS );
         }
         /* write new channel */
         pal_trx_bit_write(SR_CHANNEL, new_channel);
     }
     return pal_trx_bit_read(SR_CHANNEL);
 }
bool at86rf231_change_channel_page (uint8_t ch_page)
Apply channel page configuartion to transceiver.
change transceiver channel page
Parameters
ch_page Channel page
Returns
true if changes could be applied else false
Definition at line 398 of file at86rf231.c.
References AACK_ACK_TIME_12_SYMBOLS, AACK_ACK_TIME_2_SYMBOLS, ALTRATE_1MBPS, ALTRATE_250KBPS, ALTRATE_2MBPS, ALTRATE_500KBPS, CMD_TRX_OFF, pal_trx_bit_read(), pal_trx_bit_write(), pal_trx_reg_write(), RG_TRX_STATE, SR_AACK_ACK_TIME, SR_OQPSK_DATA_RATE, SR_RX_PDT_LEVEL, SR_TRX_STATUS, and TRX_OFF.
Referenced by at86rf231_init().
 {
     /* TRX status variale */
     tal_trx_status_t tal_trx_status = 0;
     /* Set Transceiver State = TRX_OFF */
     pal_trx_reg_write( RG_TRX_STATE, CMD_TRX_OFF );
     /* verify that state = TRX_OFF */
     while( tal_trx_status != TRX_OFF )
     {
         tal_trx_status = ( tal_trx_status_t )pal_trx_bit_read( SR_TRX_STATUS );
     }
     switch (ch_page)
     {
         case 0: /* compliant O-QPSK */
             pal_trx_bit_write(SR_OQPSK_DATA_RATE, ALTRATE_250KBPS);
             // Apply compliant ACK timing
             pal_trx_bit_write(SR_AACK_ACK_TIME, AACK_ACK_TIME_12_SYMBOLS);
             // Use full sensitivity
             pal_trx_bit_write(SR_RX_PDT_LEVEL, 0x00);
             break;
         case 2: /* non-compliant OQPSK mode 1 */
             pal_trx_bit_write(SR_OQPSK_DATA_RATE, ALTRATE_500KBPS);
             // Apply reduced ACK timing
             pal_trx_bit_write(SR_AACK_ACK_TIME, AACK_ACK_TIME_2_SYMBOLS);
             // Use full sensitivity
             pal_trx_bit_write(SR_RX_PDT_LEVEL, 0x00);
             break;
         case 16:    /* non-compliant OQPSK mode 2 */
             pal_trx_bit_write(SR_OQPSK_DATA_RATE, ALTRATE_1MBPS);
             // Apply reduced ACK timing
             pal_trx_bit_write(SR_AACK_ACK_TIME, AACK_ACK_TIME_2_SYMBOLS);
             // Use full sensitivity
             pal_trx_bit_write(SR_RX_PDT_LEVEL, 0x00);
             break;
         case 17:    /* non-compliant OQPSK mode 3 */
             pal_trx_bit_write(SR_OQPSK_DATA_RATE, ALTRATE_2MBPS);
             // Apply reduced ACK timing
             pal_trx_bit_write(SR_AACK_ACK_TIME, AACK_ACK_TIME_2_SYMBOLS);
             // Use reduced sensitivity for 2Mbit mode
             pal_trx_bit_write(SR_RX_PDT_LEVEL, 0x01);
             break;
         default:
             return false;
     }
     return true;
 }
uint8_t at86rf231_change_tx_pwr (uint8_t pwr)
Apply tx power to transceiver.
change transceiver tx power
Parameters
uint8_t pwr_value
Returns
content of pwr register or 0xFF=error
Definition at line 460 of file at86rf231.c.
References CMD_TRX_OFF, pal_trx_bit_read(), pal_trx_bit_write(), pal_trx_reg_write(), RG_TRX_STATE, SR_TRX_STATUS, SR_TX_PWR, and TRX_OFF.
 {
     if( pwr <= 0x0F)
     {
         /* TRX status variale */
         tal_trx_status_t tal_trx_status = 0;
         /* Set Transceiver State = TRX_OFF */
         pal_trx_reg_write( RG_TRX_STATE, CMD_TRX_OFF );
         /* verify that state = TRX_OFF */
         while( tal_trx_status != TRX_OFF )
         {
             tal_trx_status = ( tal_trx_status_t )pal_trx_bit_read( SR_TRX_STATUS );
         }
         /* set power level */
         pal_trx_bit_write( SR_TX_PWR, pwr );
         // 0x0   3.0 dBm
         // 0x1   2.8 dBm
         // 0x2   2.3 dBm
         // 0x3   1.8 dBm
         // 0x4   1.3 dBm
         // 0x5   0.7 dBm
         // 0x6   0.0 dBm
         // 0x7   -1 dBm
         // 0x8   -2 dBm
         // 0x9   -3 dBm
         // 0xA   -4 dBm
         // 0xB   -5 dBm
         // 0xC   -7 dBm
         // 0xD   -9 dBm
         // 0xE   -12 dBm
         // 0xF   -17 dBm
         return pal_trx_bit_read(SR_TX_PWR);
     }
     else
     {
         return 0xFF;
     }
 }
void at86rf231_ftn_pll_calibration (void)
Filter tuning and PLL calibration handling Although receiver and transmitter are very robust against these variations, it is recommended to initiate the FTN manually if the radio transceiver does not use the SLEEP state. If necessary, a calibration cycle is to be initiated in states TRX_OFF, PLL_ON or any receive state. This applies in particular for the High Data Rate Modes with a much higher sensitivity against BPF transfer function variations. The recommended calibration interval is 5 min or less.
filter and pll calibration
should be performed every 5 minutes in 2MBit-mode
Definition at line 511 of file at86rf231.c.
References CMD_FORCE_TRX_OFF, pal_trx_bit_write(), pal_trx_reg_write(), RG_TRX_STATE, and SR_FTN_START.
 {
     /* Same for both filter tuning and PLL calibration. */
     pal_trx_reg_write(RG_TRX_STATE, CMD_FORCE_TRX_OFF);
     pal_trx_bit_write(SR_FTN_START, 1);
     /* Wait tTR16 (FTN calibration time). */
     _delay_us(25);
 }
void at86rf231_init (void)
Init AT86RF231 Transceiver.
init AT86RF231 radio cip
Definition at line 37 of file at86rf231.c.
References at86rf231_change_channel_page(), AT86RF231_PART_NUM, AT86RF231_VERSION_NUM, eeprom_data::channel, eeprom_data::channel_page, CLKM_1MHZ, CLKM_SHA_DISABLE, CMD_TRX_OFF, IRQ_MASK_MODE_ON, MISO, MOSI, P_ON_TO_CLKM_AVAILABLE, PAD_CLKM_2_MA, PAL_RST_HIGH, PAL_RST_LOW, PAL_SLP_TR_LOW, pal_trx_bit_read(), pal_trx_bit_write(), pal_trx_irq_enable(), pal_trx_irq_init(), pal_trx_reg_read(), pal_trx_reg_write(), eeprom_data::pan_id, PD_ACK_BIT_SET_ENABLE, RG_IRQ_MASK, RG_PAN_ID_0, RG_PAN_ID_1, RG_PART_NUM, RG_SHORT_ADDR_0, RG_SHORT_ADDR_1, RG_TRX_STATE, RG_VERSION_NUM, RST, RST_PULSE_WIDTH_US, RX_SAFE_MODE_ENABLE, SCK, SLP_TR, SR_AACK_I_AM_COORD, SR_AACK_SET_PD, SR_CCA_MODE, SR_CHANNEL, SR_CLKM_CTRL, SR_CLKM_SHA_SEL, SR_IRQ_2_EXT_EN, SR_IRQ_MASK_MODE, SR_MAX_BE, SR_MIN_BE, SR_PAD_IO_CLKM, SR_RX_SAFE_MODE, SR_TRX_STATUS, SR_TX_PWR, eeprom_data::src_address, TAL_CCA_MODE_DEFAULT, TAL_IDLE, TAL_MAXBE_DEFAULT, TAL_MINBE_DEFAULT, TAL_PAN_COORDINATOR_DEFAULT, tal_state, TIMESTAMPING_ENABLE, trx_interface_init(), trx_irq_handler_cb(), TRX_IRQ_TRX_END, TRX_MAIN_IRQ_HDLR_IDX, TRX_OFF, TRX_PORT1_DDR, TRX_PORT2_DDR, and eeprom_data::tx_pwr.
Referenced by avr_init().
 {
     /* TRX status variale */
     tal_trx_status_t tal_trx_status = 0;
     /* Init SPI, Interrupt, IO */
     /* The following pins are output pins.  */
     TRX_PORT2_DDR |= _BV( SEL );
     TRX_PORT1_DDR |= _BV( SCK );
     TRX_PORT2_DDR |= _BV( RST );
     TRX_PORT1_DDR |= _BV( MOSI );
     TRX_PORT1_DDR |= _BV( SLP_TR );
     /* The following pins are input pins.  */
     TRX_PORT1_DDR &= ~_BV( MISO );
     trx_interface_init();
     /* Install a handler for the transceiver interrupt. */
     pal_trx_irq_init( TRX_MAIN_IRQ_HDLR_IDX, ( void * )trx_irq_handler_cb );
     pal_trx_irq_enable( TRX_MAIN_IRQ_HDLR_IDX );
     /* Set RST + SLP PIN */
     PAL_RST_HIGH();
     PAL_SLP_TR_LOW();
     _delay_us( P_ON_TO_CLKM_AVAILABLE );
     /* Apply reset pulse */
     PAL_RST_LOW();
     _delay_us( RST_PULSE_WIDTH_US );
     PAL_RST_HIGH();
     /* Verify chip version */
     while( ( pal_trx_reg_read( RG_VERSION_NUM ) != AT86RF231_VERSION_NUM ) ||
            ( pal_trx_reg_read( RG_PART_NUM ) != AT86RF231_PART_NUM ) );
     /* Set Transceiver State = TRX_OFF */
     pal_trx_reg_write( RG_TRX_STATE, CMD_TRX_OFF );
     /* verify that state = TRX_OFF */
     while( tal_trx_status != TRX_OFF )
     {
         tal_trx_status = ( tal_trx_status_t )pal_trx_bit_read( SR_TRX_STATUS );
     }
     /* write status variable */
     tal_trx_status = TRX_OFF;
     /* IO Driver strength */
     pal_trx_bit_write( SR_PAD_IO_CLKM, PAD_CLKM_2_MA );
     /* Set CLKM_SHA_DISABLE */
     pal_trx_bit_write( SR_CLKM_SHA_SEL, CLKM_SHA_DISABLE );
     /* Config clock */
     pal_trx_bit_write( SR_CLKM_CTRL, CLKM_1MHZ );
     /* ACKs for data requests, indicate pending data */
     pal_trx_bit_write( SR_AACK_SET_PD, PD_ACK_BIT_SET_ENABLE );
     /* Enable buffer protection mode */
     pal_trx_bit_write( SR_RX_SAFE_MODE, RX_SAFE_MODE_ENABLE );
     /* Enable poll mode */
     pal_trx_bit_write( SR_IRQ_MASK_MODE, IRQ_MASK_MODE_ON );
     /* The TRX_END interrupt of the transceiver is enabled. */
     pal_trx_reg_write( RG_IRQ_MASK, TRX_IRQ_TRX_END );
     /* Enable auto time stamping */
     pal_trx_bit_write( SR_IRQ_2_EXT_EN, TIMESTAMPING_ENABLE );
     /* write device addresses */
     pal_trx_reg_write( RG_PAN_ID_0,    ptr_eeprom_sram_data->pan_id); //( uint8_t )( TAL_PANID_BC_DEFAULT ) );
     pal_trx_reg_write( RG_PAN_ID_1,    ptr_eeprom_sram_data->pan_id>>8); //( uint8_t )( TAL_PANID_BC_DEFAULT >> 8 ) );
     pal_trx_reg_write( RG_SHORT_ADDR_0, ptr_eeprom_sram_data->src_address);//( uint8_t )( TAL_SHORT_ADDRESS_DEFAULT ) );
     pal_trx_reg_write( RG_SHORT_ADDR_1, ptr_eeprom_sram_data->src_address>>8);//( uint8_t )( TAL_SHORT_ADDRESS_DEFAULT >> 8 ) );
     /* configure TX_ARET; CSMA and CCA */
     pal_trx_bit_write( SR_CCA_MODE, TAL_CCA_MODE_DEFAULT );
     pal_trx_bit_write( SR_MIN_BE, TAL_MINBE_DEFAULT );
     pal_trx_bit_write( SR_AACK_I_AM_COORD, TAL_PAN_COORDINATOR_DEFAULT );
     /* set phy parameter */
     pal_trx_bit_write( SR_MAX_BE, TAL_MAXBE_DEFAULT );
     /* write channel page configuration 0, 2, 16, 17, see function for more details */
     at86rf231_change_channel_page( ptr_eeprom_sram_data->channel_page );
     /* write channel */
     pal_trx_bit_write( SR_CHANNEL, ptr_eeprom_sram_data->channel );
     /* set power level */
     pal_trx_bit_write( SR_TX_PWR, ptr_eeprom_sram_data->tx_pwr );
     // 0x0   3.0 dBm
     // 0x1   2.8 dBm
     // 0x2   2.3 dBm
     // 0x3   1.8 dBm
     // 0x4   1.3 dBm
     // 0x5   0.7 dBm
     // 0x6   0.0 dBm
     // 0x7   -1 dBm
     // 0x8   -2 dBm
     // 0x9   -3 dBm
     // 0xA   -4 dBm
     // 0xB   -5 dBm
     // 0xC   -7 dBm
     // 0xD   -9 dBm
     // 0xE   -12 dBm
     // 0xF   -17 dBm
     /* config csma */
     //trx_config_csma();
     /* write status variable */
     tal_state = TAL_IDLE;
 //    volatile uint8_t temp = 0x00;
 //
 //    temp  = pal_trx_reg_read( RG_XOSC_CTRL );
 //    pal_trx_reg_write( RG_XOSC_CTRL, 0xFF );
 //    temp  = pal_trx_reg_read( RG_XOSC_CTRL );
 }
void at86rf231_req_data (void)
Send data request and receive data with ACK and retry.
send data request command and wait for data
auto retransmit and autoack used
Definition at line 331 of file at86rf231.c.
References aMaxPHYPacketSize, at86rf231_rx_with_auto_ack(), at86rf231_tx_with_retry(), at86rf231_frame::dest_addr, eeprom_data::dest_address, at86rf231_frame::dest_pan_id, FCF_ACK_REQUEST, FCF_FRAMETYPE_MAC_CMD, FCF_SET_DEST_ADDR_MODE, FCF_SET_FRAMETYPE, FCF_SET_SOURCE_ADDR_MODE, FCF_SHORT_ADDR, at86rf231_frame::frame_control_field, at86rf231_frame::frame_length, NO_CSMA_NO_IFS, eeprom_data::pan_id, at86rf231_frame::payload, at86rf231_frame::seq_number, at86rf231_frame::src_addr, eeprom_data::src_address, and at86rf231_frame::src_pan_id.
Referenced by pm_config_protocol().
 {
      uint8_t i = 0;
      /* Build frame to transmit */
      at86rf231_tx_frame.frame_length = 67;
      at86rf231_tx_frame.frame_control_field = FCF_SET_FRAMETYPE(FCF_FRAMETYPE_MAC_CMD) |
                                               FCF_SET_DEST_ADDR_MODE(FCF_SHORT_ADDR) |
                                               FCF_SET_SOURCE_ADDR_MODE(FCF_SHORT_ADDR)|
                                               FCF_ACK_REQUEST;
      at86rf231_tx_frame.seq_number = 0xFF;
      at86rf231_tx_frame.dest_pan_id = ptr_eeprom_sram_data->pan_id;
      at86rf231_tx_frame.dest_addr = ptr_eeprom_sram_data->dest_address;
      at86rf231_tx_frame.src_pan_id = ptr_eeprom_sram_data->pan_id;
      at86rf231_tx_frame.src_addr = ptr_eeprom_sram_data->src_address;
      /* Ensure that global Interrupts are enabled */
      sei();
      /* Send frame with ACK */
      at86rf231_tx_with_retry( NO_CSMA_NO_IFS, 1 );
      /* Reset CMD */
      for(i=0;i < (aMaxPHYPacketSize - 12) ;i++)
          at86rf231_rx_frame.payload[i] = 0x00;
      /* Now wait for a config data packet */
      at86rf231_rx_with_auto_ack();
 }
void at86rf231_rx_with_auto_ack (void)
Set Transceiver State = RX_AACK_ON send ACK-Frame automatically if requested.
receive frames with auto acknowledge
Definition at line 211 of file at86rf231.c.
References at86rf231_switch_pll_on(), CMD_RX_AACK_ON, CMD_TRX_OFF, pal_trx_reg_write(), RG_TRX_STATE, RX_ON, and tal_state.
Referenced by at86rf231_req_data().
 {
     /* Set Transceiver State = TRX_OFF */
     pal_trx_reg_write( RG_TRX_STATE, CMD_TRX_OFF );
     /* Set Transceiver State = PLL_ON and until PLL locks */
     at86rf231_switch_pll_on(); //only allowed from state = TRX_OFF
     /* tal_state = receive mode */
     tal_state = RX_ON;
     /* Set Transceiver State = RX_AACK_ON  */
     pal_trx_reg_write(RG_TRX_STATE, CMD_RX_AACK_ON);
 }
void at86rf231_sleep (void)
Set Transceiver mode = sleep.
set sleep mode
Definition at line 199 of file at86rf231.c.
References CMD_FORCE_TRX_OFF, PAL_SLP_TR_HIGH, pal_trx_reg_write(), and RG_TRX_STATE.
Referenced by main().
 {
     pal_trx_reg_write(RG_TRX_STATE, CMD_FORCE_TRX_OFF);
     _delay_us(1);
     PAL_SLP_TR_HIGH();
 }
uint8_t at86rf231_switch_pll_on (void)
Switch transceiver pll on and wait until it is locked.
set transceiver state = pll on
blocks if pll does not lock
Definition at line 167 of file at86rf231.c.
References CMD_PLL_ON, pal_trx_bit_read(), pal_trx_reg_read(), pal_trx_reg_write(), RG_IRQ_STATUS, RG_TRX_STATE, SR_TRX_STATUS, TRX_IRQ_PLL_LOCK, and TRX_OFF.
Referenced by at86rf231_rx_with_auto_ack(), at86rf231_tx_with_retry(), and pm_config_protocol().
 {
     trx_irq_reason_t irq_status;
     /* Check if trx is in TRX_OFF; only from PLL_ON the following procedure is applicable */
     if (pal_trx_bit_read(SR_TRX_STATUS) != TRX_OFF)
     {
         return 0;
     }
     pal_trx_reg_read(RG_IRQ_STATUS);    /* clear PLL lock bit */
     /* Switch PLL on */
     pal_trx_reg_write(RG_TRX_STATE, CMD_PLL_ON);
     /* Check if PLL has been locked. */
     //pal_get_current_time(&start_time);
     while (1)
     {
         irq_status = (trx_irq_reason_t)pal_trx_reg_read(RG_IRQ_STATUS);
         if (irq_status & TRX_IRQ_PLL_LOCK)
         {
             break;  // PLL is locked now
         }
     }
     return 1;
 }
void at86rf231_tx (void)
Send data without ACK and Retry.
transmit frames fast, without retry
manual state transition necessary
Definition at line 229 of file at86rf231.c.
References CMD_PLL_ON, at86rf231_frame::frame_length, PAL_SLP_TR_HIGH, PAL_SLP_TR_LOW, pal_trx_frame_write(), pal_trx_reg_write(), RG_TRX_STATE, tal_state, TAL_TX_AUTO, and tx_end_irq_flag.
Referenced by send_all_data_rf231().
 {
     /* Set state PLL on */
     pal_trx_reg_write(RG_TRX_STATE, CMD_PLL_ON);
     /* pal_trx_irq_disable(TRX_MAIN_IRQ_HDLR_IDX) */
     tal_state = TAL_TX_AUTO;
     /* Reset TX_END Interrupt Flag */
     tx_end_irq_flag = 0;
     /* Toggle the SLP_TR pin triggering transmission. */
     PAL_SLP_TR_HIGH();
     asm volatile("nop\n\t" ::); // wait 65ns
     asm volatile("nop\n\t" ::);
     asm volatile("nop\n\t" ::);
     asm volatile("nop\n\t" ::);
     asm volatile("nop\n\t" ::);
     PAL_SLP_TR_LOW();
     /* Send the frame to the transceiver. */
     pal_trx_frame_write( (uint8_t *)&at86rf231_tx_frame, at86rf231_tx_frame.frame_length);
 }
void at86rf231_tx_with_retry (csma_mode_t csma_mode, bool tx_retries)
Sends frame.
tx frames with retry
Parameters
use_csma Flag indicating if CSMA is requested
tx_retries Flag indicating if transmission retries are requested by the MAC layer
csma/cd not working yet
Definition at line 260 of file at86rf231.c.
References at86rf231_switch_pll_on(), CMD_TX_ARET_ON, at86rf231_frame::frame_length, NO_CSMA_NO_IFS, NO_CSMA_WITH_IFS, PAL_SLP_TR_HIGH, PAL_SLP_TR_LOW, pal_trx_bit_read(), pal_trx_bit_write(), pal_trx_frame_write(), pal_trx_reg_write(), RG_CSMA_BE, RG_TRX_STATE, SR_MAX_CSMA_RETRIES, SR_MAX_FRAME_RETRIES, SR_TRX_STATUS, TAL_MAX_CSMA_BACKOFFS_DEFAULT, TAL_MAXBE_DEFAULT, TAL_MAXFRAMERETRIES_DEFAULT, TAL_MINBE_DEFAULT, tal_state, TAL_TX_AUTO, TX_ARET_ON, and tx_end_irq_flag.
Referenced by at86rf231_req_data().
 {
     /* TRX status variale */
     tal_trx_status_t tal_trx_status = 0;
     /* configure tx according to tx_retries */
     if (tx_retries)
     {
         pal_trx_bit_write(SR_MAX_FRAME_RETRIES, TAL_MAXFRAMERETRIES_DEFAULT);
         pal_trx_bit_write(SR_MAX_FRAME_RETRIES, 8);
     }
     else
     {
         pal_trx_bit_write(SR_MAX_FRAME_RETRIES, 0);
     }
     /* configure tx according to csma usage */
     if ((csma_mode == NO_CSMA_NO_IFS) || (csma_mode == NO_CSMA_WITH_IFS))
     {
         if (tx_retries)
         {
             pal_trx_bit_write(SR_MAX_CSMA_RETRIES, TAL_MAX_CSMA_BACKOFFS_DEFAULT);
             pal_trx_reg_write(RG_CSMA_BE, 0x00);
         }
         else
         {
             pal_trx_bit_write(SR_MAX_CSMA_RETRIES, 7);
         }
     }
     else
     {
         pal_trx_reg_write(RG_CSMA_BE, ((TAL_MAXBE_DEFAULT << 4) | TAL_MINBE_DEFAULT));
         pal_trx_bit_write(SR_MAX_CSMA_RETRIES, TAL_MAX_CSMA_BACKOFFS_DEFAULT);
     }
     /* state change from TRX_OFF to TX_ARET_ON can be done directly, too */
     at86rf231_switch_pll_on();
     do
     {
         pal_trx_reg_write(RG_TRX_STATE, CMD_TX_ARET_ON);
         _delay_us(1);
         tal_trx_status = ( tal_trx_status_t )pal_trx_bit_read( SR_TRX_STATUS );
     } while (tal_trx_status != TX_ARET_ON);
     tx_end_irq_flag = 0;
     //pal_trx_irq_disable(TRX_MAIN_IRQ_HDLR_IDX);
     tal_state = TAL_TX_AUTO;
     /* Toggle the SLP_TR pin triggering transmission. */
     PAL_SLP_TR_HIGH();
     asm volatile("nop\n\t" ::); // wait 65ns
     asm volatile("nop\n\t" ::);
     asm volatile("nop\n\t" ::);
     asm volatile("nop\n\t" ::);
     asm volatile("nop\n\t" ::);
     PAL_SLP_TR_LOW();
     /* Send the frame to the transceiver. */
     pal_trx_frame_write( (uint8_t *)&at86rf231_tx_frame, at86rf231_tx_frame.frame_length);
     while(tx_end_irq_flag == 0)
     {
     }
 }
void delay_us (uint16_t usec)
void handle_received_frame_irq (void)
Handle received frame interrupt.
Interrupt handler for received frames.
This function handles transceiver interrupts for received frames and uploads the frames from the trx.
Definition at line 625 of file at86rf231.c.
References CMD_PLL_ON, LENGTH_FIELD_LEN, LQI_LEN, pal_trx_bit_read(), pal_trx_frame_read(), pal_trx_reg_read(), pal_trx_reg_write(), RG_PHY_ED_LEVEL, RG_TRX_STATE, and SR_RX_CRC_VALID.
Referenced by trx_irq_handler_cb().
 {
     static uint8_t ed_value;
     uint8_t frame_length;
     /* Get ED value; needed to normalize LQI. */
     ed_value = pal_trx_reg_read( RG_PHY_ED_LEVEL );
     /* Get frame length from transceiver. */
     pal_trx_frame_read( &frame_length, LENGTH_FIELD_LEN );
     /* Check for valid frame length. */
     if( frame_length > 127 )
     {
         return;
     }
     /* check if crc is valid */
     if( pal_trx_bit_read(SR_RX_CRC_VALID) )
     {
         /*
          * The PHY header is also included in the frame, hence the frame length
          * is incremented by 1. In addition to that, the LQI needs to be uploaded, too.
          */
         frame_length += LQI_LEN + LENGTH_FIELD_LEN;
         /* Upload frame and store it to the buffer */
         //pal_trx_frame_read( (uint8_t *)tal_rx_buffer, frame_length );
         pal_trx_frame_read( (uint8_t*)&at86rf231_rx_frame, frame_length );
     }
     else
     {
         // CRC ERROR
     }
     /* Check if receive buffer is available */
     if( NULL == &at86rf231_rx_frame )
     {
         /* Use a fast state change instead of set_trx_state(). */
         pal_trx_reg_write( RG_TRX_STATE, CMD_PLL_ON );
     }
     else
     {
         /*
          * Trx returns to RX_AACK_ON automatically, if this was its previous state.
          * Keep the following as a reminder, if receiver is used with RX_ON instead.
          */
         //pal_trx_reg_write(RG_TRX_STATE, CMD_RX_AACK_ON);
     }
 }
static void pal_global_irq_disable (void) inline static
Disables the global interrupt.
Definition at line 364 of file at86.h.
References DISABLE_GLOBAL_IRQ.
 {
     DISABLE_GLOBAL_IRQ();
 }
static void pal_global_irq_enable (void) inline static
Enables the global interrupt.
Definition at line 355 of file at86.h.
References ENABLE_GLOBAL_IRQ.
 {
     ENABLE_GLOBAL_IRQ();
 }
uint8_t pal_trx_bit_read (uint8_t addr, uint8_t mask, uint8_t pos)
read specified bit from transceiver
read specified bit from transceiver
This function handles the non-blocking SPI transfer. Subregister read
Parameters
addr offset of the register
mask bit mask of the subregister
pos bit position of the subregister
Returns
value of the read bit(s)
Definition at line 323 of file pal_trx_access.c.
References pal_trx_reg_read().
Referenced by at86rf231_change_channel(), at86rf231_change_channel_page(), at86rf231_change_tx_pwr(), at86rf231_init(), at86rf231_switch_pll_on(), at86rf231_tx_with_retry(), handle_received_frame_irq(), pm_config_protocol(), and trx_irq_handler_cb().
 {
     uint8_t ret;
     ret = pal_trx_reg_read(addr);
     ret &= mask;
     ret >>= pos;
     return ret;
 }
void pal_trx_bit_write (uint8_t reg_addr, uint8_t mask, uint8_t pos, uint8_t new_value)
write specified bit to transceiver
write specified bit to transceiver
Parameters
[in] reg_addr Offset of the register
[in] mask Bit mask of the subregister
[in] pos Bit position of the subregister
[out] new_value Data, which is muxed into the register
Definition at line 342 of file pal_trx_access.c.
References pal_trx_reg_read(), and pal_trx_reg_write().
Referenced by at86rf231_change_channel(), at86rf231_change_channel_page(), at86rf231_change_tx_pwr(), at86rf231_ftn_pll_calibration(), at86rf231_init(), and at86rf231_tx_with_retry().
 {
     uint8_t current_reg_value;
     current_reg_value = pal_trx_reg_read(reg_addr);
     current_reg_value &= ~mask;
     new_value <<= pos;
     new_value &= mask;
     new_value |= current_reg_value;
     pal_trx_reg_write(reg_addr, new_value);
 }
void pal_trx_frame_read (uint8_t * data, uint8_t length)
Upload frame from transceiver.
Upload frame from transceiver.
This function reads the frame buffer of the transceiver.
Parameters
[out] data Pointer to the location to store frame
[in] length Number of bytes to be read from the frame buffer.
Definition at line 199 of file pal_trx_access.c.
References SPI_DUMMY_VALUE, SPI_WAIT, SS_HIGH, SS_LOW, and TRX_CMD_FR.
Referenced by handle_received_frame_irq().
 {
     /* Assumption: This function is called within ISR. */
     cli();
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Send the command byte */
     SPDR0 = TRX_CMD_FR;
     SPI_WAIT();
     SPDR0 = SPI_DUMMY_VALUE;
     if (length != 1)
     {
         do
         {
             uint8_t temp;
             SPI_WAIT();
             /* Upload the received byte in the user provided location */
             temp = SPDR0;
             SPDR0 = SPI_DUMMY_VALUE; /* Do dummy write for initiating SPI read */
             *data = temp;
             data++;
             length--;
         } while (length > 1);
     }
     SPI_WAIT(); /* Wait until last bytes is transmitted. */
     *data = SPDR0;
     /* Stop the SPI transaction by setting SEL high */
     SS_HIGH();
     sei();
 }
void pal_trx_frame_write (uint8_t * data, uint8_t length)
write frame to transceiver
write frame to transceiver
This function writes data into the frame buffer of the transceiver
Parameters
[in] data Pointer to data to be written into frame buffer
[in] length Number of bytes to be written into frame buffer
Definition at line 244 of file pal_trx_access.c.
References SPI_IRQ_ENABLE, SPI_WAIT, SPI_WRITE, SS_HIGH, SS_LOW, and TRX_CMD_FW.
Referenced by at86rf231_tx(), and at86rf231_tx_with_retry().
 {
 #ifndef NON_BLOCKING_SPI
     cli();
     /* Assumption: The TAL has already disabled the trx interrupt. */
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Start SPI transfer by sending the command byte */
     SPDR0 = TRX_CMD_FW;
     SPI_WAIT();
     do
     {
         uint8_t temp = *data;
         data++;
         length--;
         SPI_WAIT();
         SPDR0 = temp;
     } while (length > 0);
     SPI_WAIT(); /* Wait until last bytes is transmitted. */
     /* Stop the SPI transaction by setting SEL high */
     SS_HIGH();
     sei();
 #else
     spi_state = SPI_WRITE;
     spi_remaining_bytes = length;
     spi_data_ptr = data;
     SPI_IRQ_ENABLE();
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Start SPI transfer by sending the command byte */
     SPDR0 = TRX_CMD_FW;
 #endif
 }
static void pal_trx_irq_disable (trx_irq_hdlr_idx_t trx_irq_num) inline static
Disables the transceiver interrupt.
Parameters
trx_irq_num One of several interrupt lines provided by the transceiver
Definition at line 335 of file at86.h.
References DISABLE_TRX_IRQ.
 {
     DISABLE_TRX_IRQ(trx_irq_num);
 }
static void pal_trx_irq_enable (trx_irq_hdlr_idx_t trx_irq_num) inline static
Enables the transceiver interrupt.
Parameters
trx_irq_num One of several interrupt lines provided by the transceiver
Definition at line 324 of file at86.h.
References ENABLE_TRX_IRQ.
Referenced by at86rf231_init().
 {
     ENABLE_TRX_IRQ(trx_irq_num);
 }
static void pal_trx_irq_flag_clr (trx_irq_hdlr_idx_t trx_irq_num) inline static
Clears the transceiver interrupt.
Parameters
trx_irq_num One of several interrupt lines provided by the transceiver
Definition at line 346 of file at86.h.
References CLEAR_TRX_IRQ.
 {
     CLEAR_TRX_IRQ(trx_irq_num);
 }
void pal_trx_irq_init (trx_irq_hdlr_idx_t trx_irq_num, void * trx_irq_cb)
init external interrupt
Parameters
Interrupt number
Interrupt callback function
init external interrupt
This function sets the microcontroller specific registers responsible for handling the transceiver interrupts
Parameters
trx_irq_num Transceiver interrupt line to be initialized
trx_irq_cb Callback function for the given transceiver interrupt
Definition at line 552 of file pal_trx_access.c.
References irq_handler, TRX_MAIN_IRQ_HDLR_IDX, and TRX_TSTAMP_IRQ_HDLR_IDX.
Referenced by at86rf231_init().
 {
     /*
      * Set the handler function.
      * The handler is set before enabling the interrupt to prepare for spurious
      * interrupts, that can pop up the moment they are enabled
      */
     irq_handler[trx_irq_num] = (irq_handler_t)trx_irq_cb;
     if (trx_irq_num == TRX_MAIN_IRQ_HDLR_IDX)
     {
         /* Init Main TRX interrupt */
         /* Select rising edge */
         EICRA |= _BV(ISC00) | _BV(ISC01);
         /* clear pending interrupt */
         EIFR = _BV(INTF0);
     }
 #ifndef ANTENNA_DIVERSITY
     else if (trx_irq_num == TRX_TSTAMP_IRQ_HDLR_IDX)
     {
         /* Init RX TIME STAMP interrupt */
         /* The input capture interrupt of timer is disabled */
         TIMSK1 &= ~(_BV(ICIE1));
         /* Rising edge on input capture pin used to trigger IRQ */
         TCCR1B |= (_BV(ICES1));
         /* Input capture flag is cleared */
         TIFR1 |= (_BV(ICF1));
     }
 #endif
 }
uint8_t pal_trx_reg_read (uint8_t addr)
read register from transceiver
read register from transceiver
This function reads the current value from a transceiver register.
Parameters
addr Specifies the address of the trx register from which the data shall be read
Returns
value of the register read
Definition at line 149 of file pal_trx_access.c.
References ENTER_TRX_REGION, LEAVE_TRX_REGION, READ_ACCESS_COMMAND, SPI_DUMMY_VALUE, SPI_IDLE, SPI_WAIT, SS_HIGH, and SS_LOW.
Referenced by at86rf231_init(), at86rf231_switch_pll_on(), handle_received_frame_irq(), pal_trx_bit_read(), pal_trx_bit_write(), and trx_irq_handler_cb().
 {
     uint8_t register_value;
     cli();
     ENTER_TRX_REGION();
 #ifdef NON_BLOCKING_SPI
     while (spi_state != SPI_IDLE)
     {
         /* wait until SPI gets available */
     }
 #endif
     /* Prepare the command byte */
     addr |= READ_ACCESS_COMMAND;
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Send the Read command byte */
     SPDR0 = addr;
     SPI_WAIT();
     /* Do dummy read for initiating SPI read */
     SPDR0 = SPI_DUMMY_VALUE;
     SPI_WAIT();
     /* Read the byte received */
     register_value = SPDR0;
     /* Stop the SPI transaction by setting SEL high */
     SS_HIGH();
     LEAVE_TRX_REGION();
     sei();
     return register_value;
 }
void pal_trx_reg_write (uint8_t addr, uint8_t data)
write register to transceiver
write register to transceiver
Writes data into a transceiver register
This function writes a value into transceiver register.
Parameters
addr Address of the trx register
data Data to be written to trx register
Definition at line 106 of file pal_trx_access.c.
References ENTER_TRX_REGION, LEAVE_TRX_REGION, SPI_IDLE, SPI_WAIT, SS_HIGH, SS_LOW, and WRITE_ACCESS_COMMAND.
Referenced by at86rf231_change_channel(), at86rf231_change_channel_page(), at86rf231_change_tx_pwr(), at86rf231_ftn_pll_calibration(), at86rf231_init(), at86rf231_rx_with_auto_ack(), at86rf231_sleep(), at86rf231_switch_pll_on(), at86rf231_tx(), at86rf231_tx_with_retry(), handle_received_frame_irq(), pal_trx_bit_write(), pm_config_protocol(), and trx_irq_handler_cb().
 {
     cli();
     ENTER_TRX_REGION();
 #ifdef NON_BLOCKING_SPI
     while (spi_state != SPI_IDLE)
     {
         /* wait until SPI gets available */
     }
 #endif
     /* Prepare the command byte */
     addr |= WRITE_ACCESS_COMMAND;
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Send the Read command byte */
     SPDR0 = addr;
     SPI_WAIT();
     /* Write the byte in the transceiver data register */
     SPDR0 = data;
     SPI_WAIT();
     /* Stop the SPI transaction by setting SEL high */
     SS_HIGH();
     LEAVE_TRX_REGION();
     sei();
 }
void trx_interface_init (void)
init spi interace
init spi interace
This function initializes the transceiver interface.
Definition at line 82 of file pal_trx_access.c.
References TRX_INIT.
Referenced by at86rf231_init().
 {
     TRX_INIT();
 }
void trx_irq_handler_cb (void)
Transceiver interrupt handler.
external interrupt handler
This function handles the transceiver generated interrupts.
Definition at line 531 of file at86rf231.c.
References handle_received_frame_irq(), pal_trx_bit_read(), pal_trx_reg_read(), pal_trx_reg_write(), RG_IRQ_STATUS, RG_TRX_STATE, RX_ON, SR_TRAC_STATUS, tal_state, TAL_TX_AUTO, TAL_TX_DONE, TRAC_INVALID, TRX_IRQ_AMI, TRX_IRQ_BAT_LOW, TRX_IRQ_CCA_ED_READY, TRX_IRQ_PLL_UNLOCK, TRX_IRQ_RX_START, TRX_IRQ_TRX_END, TRX_IRQ_TRX_UR, and tx_end_irq_flag.
Referenced by at86rf231_init().
 {
     trx_irq_reason_t trx_irq_cause;
     trx_trac_status_t trx_trac_status;
     /* what was the reason for the interrupt */
     trx_irq_cause = (trx_irq_reason_t)pal_trx_reg_read(RG_IRQ_STATUS);
     if (trx_irq_cause & TRX_IRQ_TRX_END)
     {
         /*
          * TRX_END reason depends on if the trx is currently used for
          * transmission or reception.
          */
         if (tal_state == TAL_TX_AUTO)
         {
             /* Get the result and push it to the queue. */
             if (trx_irq_cause & TRX_IRQ_TRX_UR)
             {
                 trx_trac_status = TRAC_INVALID;
             }
             else
             {
                 /* Check if no ACK was received */
                 trx_trac_status = (trx_trac_status_t)pal_trx_bit_read(SR_TRAC_STATUS);
                 pal_trx_reg_write(RG_TRX_STATE, RX_ON);
             }
             tx_end_irq_flag = 1;
             tal_state = TAL_TX_DONE;    // Further handling is done by tx_done_handling()
         }
         else   /* Other tal_state than TAL_TX_... */
         {
             /* address match interrupt */
             if (trx_irq_cause & TRX_IRQ_AMI)
             {
                 /* Handle rx interrupt. */
                 handle_received_frame_irq();    // see tal_rx.c
             }
         }
     }
 //#define DEBUG 1
 #if (DEBUG > 0)
     /* Other IRQ than TRX_END */
     if (trx_irq_cause != TRX_IRQ_TRX_END)
     {
         /* PLL_LOCK interrupt migth be set, because poll mode is enabled. */
         /*
         if (trx_irq_cause & TRX_IRQ_PLL_LOCK)
         {
             ASSERT("unexpected IRQ: TRX_IRQ_PLL_LOCK" == 0);
         }
         */
         if (trx_irq_cause & TRX_IRQ_PLL_UNLOCK)
         {
             //ASSERT("unexpected IRQ: TRX_IRQ_PLL_UNLOCK" == 0);
         }
         /* RX_START interrupt migth be set, because poll mode is enabled. */
         if (trx_irq_cause & TRX_IRQ_RX_START)
         {
             //ASSERT("unexpected IRQ: TRX_IRQ_RX_START" == 0);
         }
         if (trx_irq_cause & TRX_IRQ_CCA_ED_READY)
         {
             //ASSERT("unexpected IRQ: TRX_IRQ_CCA_ED_READY" == 0);
         }
         /* AMI interrupt might set, because poll mode is enabled. */
         if (trx_irq_cause & TRX_IRQ_AMI)
         {
             //ASSERT("unexpected IRQ: TRX_IRQ_AMI" == 0);
         }
         if (trx_irq_cause & TRX_IRQ_TRX_UR)
         {
             //ASSERT("unexpected IRQ: TRX_IRQ_TRX_UR" == 0);
         }
         if (trx_irq_cause & TRX_IRQ_BAT_LOW)
         {
             //ASSERT("unexpected IRQ: TRX_IRQ_BAT_LOW" == 0);
         }
     }
 #endif
 }/* trx_irq_handler_cb() */