SPIKE 1.1: Temperature Sensor DS620
Temperature Sensor DS620
Functions
int16_t ds620_get_temperature (void)
Get the temperature value of the sensor.
void ds620_init (void)
Initializes the DS620.
void ds620_start_convert (void)
Starts a conversation or wake up from sleep.
void ds620_stop_convert (void)
Set DS620 to sleep.
void ds620_twi_init (void)
Initializes the TWI of the temperature sensor.
uint8_t ds620_twi_read (uint8_t ack)
Read one byte.
void ds620_twi_send (unsigned char data)
Send one byte.
unsigned char ds620_twi_start (unsigned char addr)
Send an TWI Start condition.
void ds620_twi_stop (void)
Send a stop condition.
Detailed Description
The Temperature Sensor DS620 module includes project-specific definitions and function prototypes, such as the Temperature Sensor DS620 initialization function.
Function Documentation
int16_t ds620_get_temperature (void)
Get the temperature value of the sensor.
Definition at line 96 of file ds620.c.
References ds620_twi_read(), ds620_twi_send(), ds620_twi_start(), and ds620_twi_stop().
Referenced by main(), and pm_config_protocol().
 {
     uint8_t value_LSB = 0;
     uint8_t value_MSB = 0;
     int16_t value_receive = 0;
     ds620_twi_start( 0x90 | ( 0 << 1 ) );               // TWI-Verbindung aufbauen
     ds620_twi_send( 0xAA );                             // DS620 Adresse auf Temperaturwert
     ds620_twi_start( 0x91 | ( 0 << 1 ) );               // Temperaturwert auslesen starten
     value_MSB = ds620_twi_read( 1 );                    // 1.Temperatur-Byte auslesen
     value_LSB = ds620_twi_read( 0 );                    // 2.Temperatur-Byte auslesen und
     value_receive = (int16_t) ((value_MSB << 8) | value_LSB);
     ds620_twi_stop();                                   // TWI-Verbindung beenden
     return value_receive;
 }
void ds620_init (void)
Initializes the DS620.
Definition at line 70 of file ds620.c.
References ds620_twi_init(), ds620_twi_send(), ds620_twi_start(), and ds620_twi_stop().
Referenced by avr_init().
 {
     ds620_twi_init();                       // TWI initialization
     ds620_twi_start( 0x90 | ( 0 << 1 ) );   // start TWI connection
     ds620_twi_send( 0xAC );                 // Configuration Register MS Byte
     ds620_twi_send( 0x08);                  // 12 Bit resolution, Continuous conversion mode
     ds620_twi_start( 0x90 | ( 0 << 1 ) );   // start TWI connection
     ds620_twi_send( 0x51 );                 // start convert
     ds620_twi_stop();                       // stop TWI connection
 }
void ds620_start_convert (void)
Starts a conversation or wake up from sleep.
Definition at line 89 of file ds620.c.
References ds620_twi_send(), ds620_twi_start(), and ds620_twi_stop().
Referenced by main().
 {
     ds620_twi_start( 0x90 | ( 0 << 1 ) );   // start TWI connection
     ds620_twi_send( 0x51 );                 // start convert
     ds620_twi_stop();                       // stop TWI connection
 }
void ds620_stop_convert (void)
Set DS620 to sleep.
Definition at line 82 of file ds620.c.
References ds620_twi_send(), ds620_twi_start(), and ds620_twi_stop().
Referenced by main().
 {
     ds620_twi_start( 0x90 | ( 0 << 1 ) );   // start TWI connection
     ds620_twi_send( 0x22 );                 // stop convert
     ds620_twi_stop();                       // stop TWI connection
 }
void ds620_twi_init (void)
Initializes the TWI of the temperature sensor.
Definition at line 23 of file ds620.c.
Referenced by ds620_init().
 {
     DDRC &= ~(1 << PINC0);      // TWI SCL
     PORTC |= (1 << PINC0);      // TWI SCL
     DDRC &= ~(1 << PINC1);      // TWI SDA
     PORTC |= (1 << PINC1);      // TWI SDA
     TWBR=0x04;      // TWI Bit Rate Register
     TWCR=0x00;      // TWI Control Register
     TWSR=0xF8;      // TWI Status Register (1 = value of the prescaler bits)
 }
uint8_t ds620_twi_read (uint8_t ack)
Read one byte.
Parameters
ack 0: NACK, 1: ACK
Definition at line 55 of file ds620.c.
Referenced by ds620_get_temperature().
 {
     if( ack )
     TWCR = ( 1 << TWINT ) | ( 1 << TWEA ) | ( 1 << TWEN );
     else
     TWCR = ( 1 << TWINT ) | ( 1 << TWEN );
     while( !( TWCR & ( 1 << TWINT ) ) );
     return ( TWDR );
 }
void ds620_twi_send (unsigned char data)
Send one byte.
Parameters
data Byte to send.
Definition at line 48 of file ds620.c.
Referenced by ds620_get_temperature(), ds620_init(), ds620_start_convert(), and ds620_stop_convert().
 {
     TWDR = data;
     TWCR = ( 1 << TWINT ) | ( 1 << TWEN );
     while( !( TWCR & ( 1 << TWINT ) ) );
 }
unsigned char ds620_twi_start (unsigned char addr)
Send an TWI Start condition.
Parameters
addr Chip address.
Definition at line 36 of file ds620.c.
Referenced by ds620_get_temperature(), ds620_init(), ds620_start_convert(), and ds620_stop_convert().
 {
     TWCR = ( 1 << TWINT ) | ( 1 << TWSTA ) | ( 1 << TWEN );
     while( !( TWCR & ( 1 << TWINT ) ) );
     TWDR = addr;
     TWCR = ( 1 << TWINT ) | ( 1 << TWEN );
     while( !( TWCR & ( 1 << TWINT ) ) );
     if( ( TWSR & 0xF8 ) != 0x40 )
     return ( 0 );
     return ( 1 );
 }
void ds620_twi_stop (void)
Send a stop condition.
Definition at line 65 of file ds620.c.
Referenced by ds620_get_temperature(), ds620_init(), ds620_start_convert(), and ds620_stop_convert().
 {
     TWCR = ( 1 << TWINT ) | ( 1 << TWSTO ) | ( 1 << TWEN );
 }