SPIKE 1.1: Semtech SX8723c
Semtech SX8723c
Modules
Semtech SX8723c Software TWI
Macros
#define F_CPU (10000000UL)
#define STRAIN_GAUGE_OFF PORTD |= (1 << PIND7)
Pin to turn the supply of the strain gauges off.
#define STRAIN_GAUGE_ON PORTD &= ~(1 << PIND7)
Pin to turn the supply of the strain gauges on.
#define SX8723c_DATA_AVERAGE 100
maximal 65536, average in auto-offset function
#define TRESHOLD_PGA3_OFFSET 2800
this is the high level of the hardware offset
#define TRESHOLD_PGA3_OFFSET_HIGH 2800
this is the high level of the hardware offset
#define TRESHOLD_PGA3_OFFSET_LOW -2800
this is the low level of the hardware offset
Enumerations
enum sign_t { SIGN_POSITIV = 0, SIGN_NEGATIVE = 1 }
Functions
void SX8723c_auto_offset (uint8_t device)
This function compensate an offset automatically.
void SX8723c_get_value (uint8_t device, int16_t *data)
This function returns the actually measurement value.
void SX8723c_init (uint8_t device)
This function initialize the SX8723c.
void SX8723c_send_request (uint8_t device)
This function starts an conversation on the SX8723c.
void SX8723c_set_PGA3_offset (uint8_t device, sign_t sign, uint8_t offset)
This function sets an new PGA3 offset.
void SX8723c_sleep (uint8_t device)
This function sets the SX8723c in sleep mode.
void SX8723c_start (uint8_t device)
This function sets the SX8723c in normal mode (back from sleep mode).
Variables
eeprom_data eeprom_sram_data
EEPROM image in SRAM.
eeprom_data * ptr_eeprom_sram_data
pointer to EEPROM image in SRAM
RC Register
#define REG_RC_EN 0x30
GPIO Registers
#define REG_OUT 0x40
D0 and D1 pads data output and direction control.
#define REG_IN 0x41
D0 and D1 pads input data.
#define REG_TIMEOUT 0x42
Enable/Disable I2C timeout.
#define REG_EXT_ADD 0x43
ADC Registers
#define REG_AC_OUT_LSB 0x50
LSB of ADC result.
#define REG_AC_OUT_MSB 0x51
MSB of ADC result.
#define REG_AC_CFG0 0x52
ADC conversion control.
#define REG_AC_CFG1 0x53
ADC conversion control.
#define REG_AC_CFG2 0x54
ADC conversion control.
#define REG_AC_CFG3 0x55
ADC conversion control.
#define REG_AC_CFG4 0x56
ADC conversion control.
#define REG_AC_CFG5 0x57
Mode Register
#define REG_MODE 0x70
Defines for RegRCen register (0x30)
#define RC_DISABLE (0 << 0)
Disable RC oscillator. Set 0 for low power mode.
#define RC_ENABLE (1 << 0)
Defines for RegQut register (0x40)
#define D0_DIR_INPUT (0 << 4)
D0 pad direction as input.
#define D0_DIR_OUTPUT (1 << 4)
D0 pad direction as output.
#define D1_DIR_INPUT (0 << 5)
D1 pad direction as input.
#define D1_DIR_OUTPUT (1 << 5)
D1 pad direction as output.
#define REG_OUT_RESERVED_PIN (0 << 0)|(0 << 1)|(1 << 6)|(1 << 7)
Defines for RegTimeout register (0x42)
#define I2C_TIMEOUT_DISABLE (0 << 5)
D0 pad direction as input.
#define I2C_TIMEOUT_ENABLE (1 << 5)
D0 pad direction as output.
#define REG_TIMEOUT_RESERVED_PIN (0 << 0)|(0 << 1)|(0 << 2)|(0 << 3)|(0 << 4)|(0 << 6)|(0 << 7)
Defines for RegExtAdd register (0x43)
#define INTERNAL_I2C_ADDRESS 0x00
Use standard I2C address.
#define EXTERNAL_I2C_ADDRESS 0x96
Defines for RegACCfg0 register (0x52)
#define REG_ACCFG0_RESERVED_PIN (0 << 0)
Please write this reset values every time.
#define SET_CONTINUOUS_MODE (1 << 1)
Sets the continuous ADC conversion mode.
#define OSR_8 (0 << 2)
Sets the ADC over-sampling rate = 8.
#define OSR_16 (1 << 2)
Sets the ADC over-sampling rate = 16.
#define OSR_32 (2 << 2)
Sets the ADC over-sampling rate = 32.
#define OSR_64 (3 << 2)
Sets the ADC over-sampling rate = 64.
#define OSR_128 (4 << 2)
Sets the ADC over-sampling rate = 128.
#define OSR_256 (5 << 2)
Sets the ADC over-sampling rate = 256.
#define OSR_512 (6 << 2)
Sets the ADC over-sampling rate = 512.
#define OSR_1024 (7 << 2)
Sets the ADC over-sampling rate = 1024.
#define NELCONV_1 (0 << 5)
Nummer of elementary conversation = 1.
#define NELCONV_2 (1 << 5)
Nummer of elementary conversation = 2.
#define NELCONV_4 (2 << 5)
Nummer of elementary conversation = 4.
#define NELCONV_8 (3 << 5)
Nummer of elementary conversation = 8.
#define START_CONVERSION (1 << 7)
Defines for RegACCfg1 register (0x53)
#define ADC_DISABLE (0 << 0)
Disable ADC.
#define ADC_ENABLE (1 << 0)
Enable ADC.
#define PGA1_DISABLE (0 << 1)
Disable PGA1.
#define PGA1_ENABLE (1 << 1)
Enable PGA1.
#define PGA2_DISABLE (0 << 2)
Disable PGA2.
#define PGA2_ENABLE (1 << 2)
Enable PGA2.
#define PGA3_DISABLE (0 << 3)
Disable PGA3.
#define PGA3_ENABLE (1 << 3)
Enable PGA3.
#define IB_AMP_PGA_25 (0 << 4)
Bias current for the PGA = 25%.
#define IB_AMP_PGA_50 (1 << 4)
Bias current for the PGA = 50%.
#define IB_AMP_PGA_75 (2 << 4)
Bias current for the PGA = 75%.
#define IB_AMP_PGA_100 (3 << 4)
Bias current for the PGA = 100%.
#define IB_AMP_ADC_25 (0 << 6)
Bias current for the ADC = 25%.
#define IB_AMP_ADC_50 (1 << 6)
Bias current for the ADC = 50%.
#define IB_AMP_ADC_75 (2 << 6)
Bias current for the ADC = 75%.
#define IB_AMP_ADC_100 (3 << 6)
Defines for RegACCfg2 register (0x54)
#define PGA2_GAIN_1 (0 << 4)
PGA2 gain = 1.
#define PGA2_GAIN_2 (1 << 4)
PGA2 gain = 2.
#define PGA2_GAIN_5 (2 << 4)
PGA2 gain = 5.
#define PGA2_GAIN_10 (3 << 4)
PGA2 gain = 10.
#define OSF_62K5HZ (0 << 6)
ADC Sampling Frequency = 62.5 kHz.
#define OSF_125KHZ (1 << 6)
ADC Sampling Frequency = 125 kHz.
#define OSF_250KHZ (2 << 6)
ADC Sampling Frequency = 250 kHz.
#define OSF_500KHZ (3 << 6)
Defines for RegACCfg3 register (0x55)
#define PGA1_GAIN_1 (0 << 7)
PGA1 gain = 1.
#define PGA1_GAIN_10 (1 << 7)
Defines for RegACCfg4 register (0x56)
#define REG_ACCFG4_RESERVED_PIN (0 << 7)
Defines for RegACCfg5 register (0x57)
#define VMUX_VBATT (0 << 0)
Reference is Vbatt.
#define VMUX_VREF (1 << 0)
Reference is Vref.
#define AMUX_AC0_AC1 (0 << 1)
Channel: AC0 (VSS) - AC1 (VREF).
#define AMUX_AC1_AC0 (0 << 1)
Channel: AC1 (VREF) - AC0 (VSS).
#define AMUX_AC2_AC3 (1 << 1)
Channel: AC2 - AC2.
#define AMUX_AC3_AC2 (1 << 1)
Channel: AC3 - AC2.
#define AMUX_AC5_AC4 (2 << 1)
Channel: AC5 - AC4.
#define AMUX_AC4_AC5 (2 << 1)
Channel: AC4 - AC5.
#define AMUX_AC0 (0 << 1)
Channel: AC0 (VSS) - AC0 (VSS).
#define AMUX_AC1 (1 << 1)
Channel: AC1 (VREF) - AC0 (VSS).
#define AMUX_AC2 (2 << 1)
Channel: AC2 - AC0 (VSS).
#define AMUX_AC3 (3 << 1)
Channel: AC3 - AC0 (VSS).
#define AMUX_AC4 (4 << 1)
Channel: AC4 - AC0 (VSS).
#define AMUX_AC5 (5 << 1)
Channel: AC5 - AC0 (VSS).
#define AMUX_SIGN_STRAIGHT (0 << 4)
Sign is straight.
#define AMUX_SIGN_CROSS (1 << 4)
Sign is cross.
#define AMUX_MODE_DIFFERENTIAL_INPUT (0 << 5)
Mode: Differential input.
#define AMUS_MODE_SINGLE_ENDED_INPUT (1 << 5)
Mode: Single ended input.
#define DEF_CONFIG (1 << 6)
Defines for RegMode register (0x70)
#define VREF_D1_IN_ENABLE (1 << 0)
Enable external Vref on D1 pin.
#define VREF_D0_OUT_ENABLE (1 << 1)
Enable Vref output on D0 pin.
#define MULTI_FORCE_OFF (1 << 2)
Force charge pump Off.
#define MULTI_FORCE_ON (1 << 3)
Force charge pump On. Takes priority.
#define CHOP_0 (0 << 4)
Chopping control state = 0.
#define CHOP_1 (1 << 4)
Chopping control state = 1.
#define CHOP_NELCONV (2 << 4)
Chopping control at Nelconv rate.
#define CHOP_NELCONV_0_5 (3 << 4)
Chopping control at Nelconv/2 rate.
#define REG_MODE_RESERVED_PIN (0 << 6)|(1 << 7)
Detailed Description
The Semtech SX8723c module includes project-specific definitions and function prototypes, such as the SX8723c initialization function.
Macro Definition Documentation
#define ADC_DISABLE (0 << 0)
Disable ADC.
Definition at line 152 of file SX8723c.h.
#define ADC_ENABLE (1 << 0)
Enable ADC.
Definition at line 153 of file SX8723c.h.
#define AMUS_MODE_SINGLE_ENDED_INPUT (1 << 5)
Mode: Single ended input.
Definition at line 216 of file SX8723c.h.
#define AMUX_AC0 (0 << 1)
Channel: AC0 (VSS) - AC0 (VSS).
Definition at line 207 of file SX8723c.h.
#define AMUX_AC0_AC1 (0 << 1)
Channel: AC0 (VSS) - AC1 (VREF).
Definition at line 201 of file SX8723c.h.
#define AMUX_AC1 (1 << 1)
Channel: AC1 (VREF) - AC0 (VSS).
Definition at line 208 of file SX8723c.h.
#define AMUX_AC1_AC0 (0 << 1)
Channel: AC1 (VREF) - AC0 (VSS).
Definition at line 202 of file SX8723c.h.
#define AMUX_AC2 (2 << 1)
Channel: AC2 - AC0 (VSS).
Definition at line 209 of file SX8723c.h.
#define AMUX_AC2_AC3 (1 << 1)
Channel: AC2 - AC2.
Definition at line 203 of file SX8723c.h.
#define AMUX_AC3 (3 << 1)
Channel: AC3 - AC0 (VSS).
Definition at line 210 of file SX8723c.h.
#define AMUX_AC3_AC2 (1 << 1)
Channel: AC3 - AC2.
Definition at line 204 of file SX8723c.h.
#define AMUX_AC4 (4 << 1)
Channel: AC4 - AC0 (VSS).
Definition at line 211 of file SX8723c.h.
#define AMUX_AC4_AC5 (2 << 1)
Channel: AC4 - AC5.
Definition at line 206 of file SX8723c.h.
#define AMUX_AC5 (5 << 1)
Channel: AC5 - AC0 (VSS).
Definition at line 212 of file SX8723c.h.
#define AMUX_AC5_AC4 (2 << 1)
Channel: AC5 - AC4.
Definition at line 205 of file SX8723c.h.
#define AMUX_MODE_DIFFERENTIAL_INPUT (0 << 5)
Mode: Differential input.
Definition at line 215 of file SX8723c.h.
#define AMUX_SIGN_CROSS (1 << 4)
Sign is cross.
Definition at line 214 of file SX8723c.h.
#define AMUX_SIGN_STRAIGHT (0 << 4)
Sign is straight.
Definition at line 213 of file SX8723c.h.
#define CHOP_0 (0 << 4)
Chopping control state = 0.
Definition at line 227 of file SX8723c.h.
#define CHOP_1 (1 << 4)
Chopping control state = 1.
Definition at line 228 of file SX8723c.h.
#define CHOP_NELCONV (2 << 4)
Chopping control at Nelconv rate.
Definition at line 229 of file SX8723c.h.
#define CHOP_NELCONV_0_5 (3 << 4)
Chopping control at Nelconv/2 rate.
Definition at line 230 of file SX8723c.h.
#define D0_DIR_INPUT (0 << 4)
D0 pad direction as input.
Definition at line 107 of file SX8723c.h.
#define D0_DIR_OUTPUT (1 << 4)
D0 pad direction as output.
Definition at line 108 of file SX8723c.h.
#define D1_DIR_INPUT (0 << 5)
D1 pad direction as input.
Definition at line 109 of file SX8723c.h.
#define D1_DIR_OUTPUT (1 << 5)
D1 pad direction as output.
Definition at line 110 of file SX8723c.h.
#define DEF_CONFIG (1 << 6)
Selects ADC and PGA default configuration
Definition at line 217 of file SX8723c.h.
#define EXTERNAL_I2C_ADDRESS 0x96
Set two LSbits of the I2C address by external (D0 and D1).
Definition at line 126 of file SX8723c.h.
#define F_CPU (10000000UL)
Definition at line 44 of file SX8723c.h.
#define I2C_TIMEOUT_DISABLE (0 << 5)
D0 pad direction as input.
Definition at line 117 of file SX8723c.h.
#define I2C_TIMEOUT_ENABLE (1 << 5)
D0 pad direction as output.
Definition at line 118 of file SX8723c.h.
#define IB_AMP_ADC_100 (3 << 6)
Bias current for the ADC = 100%.
Definition at line 167 of file SX8723c.h.
#define IB_AMP_ADC_25 (0 << 6)
Bias current for the ADC = 25%.
Definition at line 164 of file SX8723c.h.
#define IB_AMP_ADC_50 (1 << 6)
Bias current for the ADC = 50%.
Definition at line 165 of file SX8723c.h.
#define IB_AMP_ADC_75 (2 << 6)
Bias current for the ADC = 75%.
Definition at line 166 of file SX8723c.h.
#define IB_AMP_PGA_100 (3 << 4)
Bias current for the PGA = 100%.
Definition at line 163 of file SX8723c.h.
#define IB_AMP_PGA_25 (0 << 4)
Bias current for the PGA = 25%.
Definition at line 160 of file SX8723c.h.
#define IB_AMP_PGA_50 (1 << 4)
Bias current for the PGA = 50%.
Definition at line 161 of file SX8723c.h.
#define IB_AMP_PGA_75 (2 << 4)
Bias current for the PGA = 75%.
Definition at line 162 of file SX8723c.h.
#define INTERNAL_I2C_ADDRESS 0x00
Use standard I2C address.
Definition at line 125 of file SX8723c.h.
#define MULTI_FORCE_OFF (1 << 2)
Force charge pump Off.
Definition at line 225 of file SX8723c.h.
#define MULTI_FORCE_ON (1 << 3)
Force charge pump On. Takes priority.
Definition at line 226 of file SX8723c.h.
#define NELCONV_1 (0 << 5)
Nummer of elementary conversation = 1.
Definition at line 142 of file SX8723c.h.
#define NELCONV_2 (1 << 5)
Nummer of elementary conversation = 2.
Definition at line 143 of file SX8723c.h.
#define NELCONV_4 (2 << 5)
Nummer of elementary conversation = 4.
Definition at line 144 of file SX8723c.h.
#define NELCONV_8 (3 << 5)
Nummer of elementary conversation = 8.
Definition at line 145 of file SX8723c.h.
#define OSF_125KHZ (1 << 6)
ADC Sampling Frequency = 125 kHz.
Definition at line 178 of file SX8723c.h.
#define OSF_250KHZ (2 << 6)
ADC Sampling Frequency = 250 kHz.
Definition at line 179 of file SX8723c.h.
#define OSF_500KHZ (3 << 6)
ADC Sampling Frequency = 500 kHz.
Definition at line 180 of file SX8723c.h.
#define OSF_62K5HZ (0 << 6)
ADC Sampling Frequency = 62.5 kHz.
Definition at line 177 of file SX8723c.h.
#define OSR_1024 (7 << 2)
Sets the ADC over-sampling rate = 1024.
Definition at line 141 of file SX8723c.h.
#define OSR_128 (4 << 2)
Sets the ADC over-sampling rate = 128.
Definition at line 138 of file SX8723c.h.
#define OSR_16 (1 << 2)
Sets the ADC over-sampling rate = 16.
Definition at line 135 of file SX8723c.h.
#define OSR_256 (5 << 2)
Sets the ADC over-sampling rate = 256.
Definition at line 139 of file SX8723c.h.
#define OSR_32 (2 << 2)
Sets the ADC over-sampling rate = 32.
Definition at line 136 of file SX8723c.h.
#define OSR_512 (6 << 2)
Sets the ADC over-sampling rate = 512.
Definition at line 140 of file SX8723c.h.
#define OSR_64 (3 << 2)
Sets the ADC over-sampling rate = 64.
Definition at line 137 of file SX8723c.h.
#define OSR_8 (0 << 2)
Sets the ADC over-sampling rate = 8.
Definition at line 134 of file SX8723c.h.
#define PGA1_DISABLE (0 << 1)
Disable PGA1.
Definition at line 154 of file SX8723c.h.
#define PGA1_ENABLE (1 << 1)
Enable PGA1.
Definition at line 155 of file SX8723c.h.
#define PGA1_GAIN_1 (0 << 7)
PGA1 gain = 1.
Definition at line 186 of file SX8723c.h.
#define PGA1_GAIN_10 (1 << 7)
PGA1 gain = 10.
Definition at line 187 of file SX8723c.h.
#define PGA2_DISABLE (0 << 2)
Disable PGA2.
Definition at line 156 of file SX8723c.h.
#define PGA2_ENABLE (1 << 2)
Enable PGA2.
Definition at line 157 of file SX8723c.h.
#define PGA2_GAIN_1 (0 << 4)
PGA2 gain = 1.
Definition at line 173 of file SX8723c.h.
#define PGA2_GAIN_10 (3 << 4)
PGA2 gain = 10.
Definition at line 176 of file SX8723c.h.
#define PGA2_GAIN_2 (1 << 4)
PGA2 gain = 2.
Definition at line 174 of file SX8723c.h.
#define PGA2_GAIN_5 (2 << 4)
PGA2 gain = 5.
Definition at line 175 of file SX8723c.h.
#define PGA3_DISABLE (0 << 3)
Disable PGA3.
Definition at line 158 of file SX8723c.h.
#define PGA3_ENABLE (1 << 3)
Enable PGA3.
Definition at line 159 of file SX8723c.h.
#define RC_DISABLE (0 << 0)
Disable RC oscillator. Set 0 for low power mode.
Definition at line 100 of file SX8723c.h.
#define RC_ENABLE (1 << 0)
Enable RC oscillator.
Definition at line 101 of file SX8723c.h.
#define REG_AC_CFG0 0x52
ADC conversion control.
Definition at line 83 of file SX8723c.h.
Referenced by SX8723c_init(), and SX8723c_send_request().
#define REG_AC_CFG1 0x53
ADC conversion control.
Definition at line 84 of file SX8723c.h.
Referenced by SX8723c_init(), SX8723c_sleep(), and SX8723c_start().
#define REG_AC_CFG2 0x54
ADC conversion control.
Definition at line 85 of file SX8723c.h.
Referenced by SX8723c_init().
#define REG_AC_CFG3 0x55
ADC conversion control.
Definition at line 86 of file SX8723c.h.
Referenced by SX8723c_init().
#define REG_AC_CFG4 0x56
ADC conversion control.
Definition at line 87 of file SX8723c.h.
Referenced by SX8723c_auto_offset(), SX8723c_init(), and SX8723c_set_PGA3_offset().
#define REG_AC_CFG5 0x57
ADC conversion control
Definition at line 88 of file SX8723c.h.
Referenced by SX8723c_init().
#define REG_AC_OUT_LSB 0x50
LSB of ADC result.
Definition at line 81 of file SX8723c.h.
#define REG_AC_OUT_MSB 0x51
MSB of ADC result.
Definition at line 82 of file SX8723c.h.
#define REG_ACCFG0_RESERVED_PIN (0 << 0)
Please write this reset values every time.
Definition at line 132 of file SX8723c.h.
#define REG_ACCFG4_RESERVED_PIN (0 << 7)
Please write this reset values every time.
Definition at line 193 of file SX8723c.h.
#define REG_EXT_ADD 0x43
Set address by external pin
Definition at line 75 of file SX8723c.h.
Referenced by SX8723c_init().
#define REG_IN 0x41
D0 and D1 pads input data.
Definition at line 73 of file SX8723c.h.
#define REG_MODE 0x70
Chip operating mode register
Definition at line 94 of file SX8723c.h.
Referenced by SX8723c_init().
#define REG_MODE_RESERVED_PIN (0 << 6)|(1 << 7)
Please write this reset values every time.
Definition at line 231 of file SX8723c.h.
#define REG_OUT 0x40
D0 and D1 pads data output and direction control.
Definition at line 72 of file SX8723c.h.
Referenced by SX8723c_init().
#define REG_OUT_RESERVED_PIN (0 << 0)|(0 << 1)|(1 << 6)|(1 << 7)
Please write this reset values every time.
Definition at line 111 of file SX8723c.h.
#define REG_RC_EN 0x30
RC oscillator control
Definition at line 66 of file SX8723c.h.
Referenced by SX8723c_init(), SX8723c_sleep(), and SX8723c_start().
#define REG_TIMEOUT 0x42
Enable/Disable I2C timeout.
Definition at line 74 of file SX8723c.h.
Referenced by SX8723c_init().
#define REG_TIMEOUT_RESERVED_PIN (0 << 0)|(0 << 1)|(0 << 2)|(0 << 3)|(0 << 4)|(0 << 6)|(0 << 7)
Please write this reset values every time.
Definition at line 119 of file SX8723c.h.
#define SET_CONTINUOUS_MODE (1 << 1)
Sets the continuous ADC conversion mode.
Definition at line 133 of file SX8723c.h.
#define START_CONVERSION (1 << 7)
Starts an ADC conversion.
Definition at line 146 of file SX8723c.h.
#define STRAIN_GAUGE_OFF PORTD |= (1 << PIND7)
Pin to turn the supply of the strain gauges off.
Definition at line 56 of file SX8723c.h.
Referenced by SX8723c_sleep().
#define STRAIN_GAUGE_ON PORTD &= ~(1 << PIND7)
Pin to turn the supply of the strain gauges on.
Definition at line 55 of file SX8723c.h.
Referenced by SX8723c_start().
#define SX8723c_DATA_AVERAGE 100
maximal 65536, average in auto-offset function
Definition at line 61 of file SX8723c.h.
Referenced by SX8723c_auto_offset().
#define TRESHOLD_PGA3_OFFSET 2800
this is the high level of the hardware offset
Definition at line 58 of file SX8723c.h.
Referenced by SX8723c_auto_offset().
#define TRESHOLD_PGA3_OFFSET_HIGH 2800
this is the high level of the hardware offset
Definition at line 59 of file SX8723c.h.
#define TRESHOLD_PGA3_OFFSET_LOW -2800
this is the low level of the hardware offset
Definition at line 60 of file SX8723c.h.
#define VMUX_VBATT (0 << 0)
Reference is Vbatt.
Definition at line 199 of file SX8723c.h.
#define VMUX_VREF (1 << 0)
Reference is Vref.
Definition at line 200 of file SX8723c.h.
#define VREF_D0_OUT_ENABLE (1 << 1)
Enable Vref output on D0 pin.
Definition at line 224 of file SX8723c.h.
#define VREF_D1_IN_ENABLE (1 << 0)
Enable external Vref on D1 pin.
Definition at line 223 of file SX8723c.h.
Enumeration Type Documentation
enum sign_t
Sign of a value.
Enumerator
SIGN_POSITIV
Sign positive (+).
SIGN_NEGATIVE
Sign negative (-).
Definition at line 248 of file SX8723c.h.
              {
   SIGN_POSITIV          =       0,
   SIGN_NEGATIVE         =       1
 } sign_t;
Function Documentation
void SX8723c_auto_offset (uint8_t device)
This function compensate an offset automatically.
Use only PGA3 offset. It is only possible to adjust one bridge at the time. Save offset values in the EEPROM. Preforms a hardware and software offset.
Parameters
device Strain gauge device.
Definition at line 94 of file SX8723c.c.
References device_1, device_2, device_3, device_4, EEPROM_SG_1, EEPROM_SG_2, EEPROM_SG_3, EEPROM_SG_4, eeprom_sram_data, EEPROM_SX8723C_REGACCFG4, offset, REG_AC_CFG4, eeprom_data::SG_software_offset, sw_TWI_write_single_register(), eeprom_data::SX8723c_config, SX8723c_DATA_AVERAGE, SX8723c_get_value(), SX8723c_send_request(), and TRESHOLD_PGA3_OFFSET.
Referenced by pm_config_protocol().
 {
     int16_t SG_value[4] = {0};          // measurement value of the strain gauge sensor
     int16_t *p_SG_value = SG_value;     // pointer to measurement value
     int32_t temp = 0;                   // temporary value for average
     uint8_t offset = 0;                 // offset step size
     uint8_t device_number = 0;          // device_number = address in EEPROM
     switch (device)
     {
         case device_1:
             device_number = EEPROM_SG_1;
         break;
         case device_2:
             device_number = EEPROM_SG_2;
         break;
         case device_3:
             device_number = EEPROM_SG_3;
         break;
         case device_4:
             device_number = EEPROM_SG_4;
         break;
         default:
             return;
         break;
     }
     // reset offset
     sw_TWI_write_single_register(device, REG_AC_CFG4, 0x00);
     eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGACCFG4] = 0x00;
     _delay_ms(4);   //wait until new offset is set
     // get value before offset compensation (average)
     for (uint16_t i = 0; i < SX8723c_DATA_AVERAGE; i++)
     {
         SX8723c_send_request(device);
         _delay_us(600);
         SX8723c_get_value(device, p_SG_value);  // get value
         temp += SG_value[device_number];
         SG_value[device_number] = 0;
     }
     SG_value[device_number] = temp / SX8723c_DATA_AVERAGE;
     //*********************** PGA3 offset **********************
     // check if offset compensation with PGA3 offset is possible
     // the smallest step size is 5460 [digit] in both direction
     if ((SG_value[device_number] > TRESHOLD_PGA3_OFFSET)||(SG_value[device_number] < -TRESHOLD_PGA3_OFFSET))
     {
         // value is positive and offset must be negative
         if (SG_value[device_number] > 0)
         {
             // do compensation until value < threshold
             while (SG_value[device_number] > TRESHOLD_PGA3_OFFSET)
             {
                 // increment offset PGA3
                 sw_TWI_write_single_register(device, REG_AC_CFG4, (0x40 | ++offset) );
                 _delay_ms(4);   //wait until new offset is set
                 // get new value after offset compensation (average)
                 temp = 0;
                 SG_value[device_number] = 0;
                 for (uint16_t i = 0; i < SX8723c_DATA_AVERAGE; i++)
                 {
                     SX8723c_send_request(device);
                     _delay_us(600);
                     SX8723c_get_value(device, p_SG_value);  //get value
                     temp += SG_value[device_number];
                     SG_value[device_number] = 0;
                 }
                 SG_value[device_number] = temp / SX8723c_DATA_AVERAGE;
                 // maximal offset is 63
                 // if 63 is reached it is not possible to compensate that huge offset
                 // with PGA3 offset
                 if (offset == 63)
                 {
                     return;
                 }
             }
             eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGACCFG4] = (0x40 | offset);
         }
         // value is negative and offset must be positive
         else
         {
             // do compensation until value < threshold
             while (SG_value[device_number] < -TRESHOLD_PGA3_OFFSET)
             {
                 // increment offset PGA3
                 sw_TWI_write_single_register(device, REG_AC_CFG4,  ++offset );
                 _delay_ms(4);   //wait until new offset is set
                 // get new value after offset compensation (average)
                 temp = 0;
                 SG_value[device_number] = 0;
                 for (uint16_t i = 0; i < SX8723c_DATA_AVERAGE; i++)
                 {
                     SX8723c_send_request(device);
                     _delay_us(600);
                     SX8723c_get_value(device, p_SG_value);  //get value
                     temp += SG_value[device_number];
                     SG_value[device_number] = 0;
                 }
                 SG_value[device_number] = temp / SX8723c_DATA_AVERAGE;
                 // maximal offset is 63
                 // if 63 is reached it is not possible to compensate that huge offset
                 // with PGA3 offset
                 if (offset == 63)
                 {
                     return;
                 }
             }
             eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGACCFG4] = offset;
         }
     }
     eeprom_sram_data.SG_software_offset[device_number] = SG_value[device_number];
 }
void SX8723c_get_value (uint8_t device, int16_t * data)
This function returns the actually measurement value.
Parameters
device Strain gauge device.
data Pointer to a data field as return value.
Definition at line 89 of file SX8723c.c.
References sw_TWI_read_value_registers().
Referenced by main(), and SX8723c_auto_offset().
 {
     sw_TWI_read_value_registers(device, data);
 }
void SX8723c_init (uint8_t device)
This function initialize the SX8723c.
Parameters
device Strain gauge device.
Definition at line 27 of file SX8723c.c.
References device_1, device_2, device_3, device_4, EEPROM_SG_1, EEPROM_SG_2, EEPROM_SG_3, EEPROM_SG_4, eeprom_sram_data, EEPROM_SX8723C_REGACCFG0, EEPROM_SX8723C_REGACCFG1, EEPROM_SX8723C_REGACCFG2, EEPROM_SX8723C_REGACCFG3, EEPROM_SX8723C_REGACCFG4, EEPROM_SX8723C_REGACCFG5, EEPROM_SX8723C_REGCEN, EEPROM_SX8723C_REGEXTADD, EEPROM_SX8723C_REGMODE, EEPROM_SX8723C_REGOUT, EEPROM_SX8723C_REGTIMEOUT, REG_AC_CFG0, REG_AC_CFG1, REG_AC_CFG2, REG_AC_CFG3, REG_AC_CFG4, REG_AC_CFG5, REG_EXT_ADD, REG_MODE, REG_OUT, REG_RC_EN, REG_TIMEOUT, sw_TWI_write_single_register(), and eeprom_data::SX8723c_config.
Referenced by avr_init().
 {
     uint8_t device_number = 0;
     // device_number = address in EEPROM
     switch (device)
     {
         case device_1:
             device_number = EEPROM_SG_1;
         break;
         case device_2:
             device_number = EEPROM_SG_2;
         break;
         case device_3:
             device_number = EEPROM_SG_3;
         break;
         case device_4:
             device_number = EEPROM_SG_4;
         break;
         default:
             return;
         break;
     }
     //RegRCen register (0x30)
     sw_TWI_write_single_register(device, REG_RC_EN, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGCEN]);
     //RegOut register (0x40)
     sw_TWI_write_single_register(device, REG_OUT, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGOUT]);
     //RegTimeout register (0x42)
     sw_TWI_write_single_register(device, REG_TIMEOUT, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGTIMEOUT]);
     //RegExtAdd register (0x43)
     sw_TWI_write_single_register(device, REG_EXT_ADD, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGEXTADD]);
     //AC_CFG0 register (0x52)
     sw_TWI_write_single_register(device, REG_AC_CFG0, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGACCFG0]);
     //AC_CFG1 register (0x53)
     sw_TWI_write_single_register(device, REG_AC_CFG1, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGACCFG1]);
     //AC_CFG2 register (0x54)
     sw_TWI_write_single_register(device, REG_AC_CFG2, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGACCFG2]);
     //AC_CFG3 register (0x55)
     sw_TWI_write_single_register(device, REG_AC_CFG3, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGACCFG3]);
     //AC_CFG4 register (0x56)
     sw_TWI_write_single_register(device,REG_AC_CFG4, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGACCFG4]);
     //AC_CFG5 register (0x57)
     sw_TWI_write_single_register(device, REG_AC_CFG5, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGACCFG5]);
     //RegMode register (0x70)
     sw_TWI_write_single_register(device, REG_MODE, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGMODE]);
 }
void SX8723c_send_request (uint8_t device)
This function starts an conversation on the SX8723c.
Parameters
device Strain gauge device.
Definition at line 220 of file SX8723c.c.
References EEPROM_SG_1, eeprom_sram_data, EEPROM_SX8723C_REGACCFG0, REG_AC_CFG0, sw_TWI_write_single_register(), and eeprom_data::SX8723c_config.
Referenced by main(), and SX8723c_auto_offset().
 {
     uint8_t value = eeprom_sram_data.SX8723c_config[EEPROM_SG_1][EEPROM_SX8723C_REGACCFG0];
     value &= 0xFE;
     value |= (1 << 7);
     sw_TWI_write_single_register(device, REG_AC_CFG0, value);
 }
void SX8723c_set_PGA3_offset (uint8_t device, sign_t sign, uint8_t offset)
This function sets an new PGA3 offset.
Parameters
device Strain gauge device.
sign Sign can be positive or negative.
offset New offset value.
Definition at line 282 of file SX8723c.c.
References REG_AC_CFG4, sw_TWI_read_single_register(), and sw_TWI_write_single_register().
 {
     uint8_t value = 0;
     sw_TWI_read_single_register(device, REG_AC_CFG4, &value);
     value &= 0x80;
     // sign of the offset
     value |= sign << 6;
     //value of the offset
     value |= offset << 0;
     sw_TWI_write_single_register(device, REG_AC_CFG4, value);
 }
void SX8723c_sleep (uint8_t device)
This function sets the SX8723c in sleep mode.
Parameters
device Strain gauge device.
Definition at line 230 of file SX8723c.c.
References REG_AC_CFG1, REG_RC_EN, STRAIN_GAUGE_OFF, and sw_TWI_write_single_register().
Referenced by main().
 {
     STRAIN_GAUGE_OFF;   // turn voltage of strain gauges off
     //RegRCen register (0x30)
     sw_TWI_write_single_register(device, REG_RC_EN, 0x00);
     //AC_CFG1 register (0x53)
     sw_TWI_write_single_register(device, REG_AC_CFG1, 0x00);
 }
void SX8723c_start (uint8_t device)
This function sets the SX8723c in normal mode (back from sleep mode).
Parameters
device Strain gauge device.
Definition at line 241 of file SX8723c.c.
References device_1, device_2, device_3, device_4, device_all, EEPROM_SG_1, EEPROM_SG_2, EEPROM_SG_3, EEPROM_SG_4, eeprom_sram_data, EEPROM_SX8723C_REGACCFG1, EEPROM_SX8723C_REGCEN, REG_AC_CFG1, REG_RC_EN, STRAIN_GAUGE_ON, sw_TWI_write_single_register(), and eeprom_data::SX8723c_config.
Referenced by main().
 {
     uint8_t device_number = 0;
     // device_number = address in EEPROM
     switch (device)
     {
         case device_1:
             device_number = EEPROM_SG_1;
         break;
         case device_2:
             device_number = EEPROM_SG_2;
         break;
         case device_3:
             device_number = EEPROM_SG_3;
         break;
         case device_4:
             device_number = EEPROM_SG_4;
         break;
         case device_all:
             device_number = EEPROM_SG_1;
         break;
         default:
             return;
         break;
     }
     //RegRCen register (0x30)
     sw_TWI_write_single_register(device, REG_RC_EN, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGCEN]);
     //AC_CFG1 register (0x53)
     sw_TWI_write_single_register(device, REG_AC_CFG1, eeprom_sram_data.SX8723c_config[device_number][EEPROM_SX8723C_REGACCFG1]);
     STRAIN_GAUGE_ON;    // turn voltage of strain gauges on
 }
Variable Documentation
eeprom_data eeprom_sram_data
EEPROM image in SRAM.
Definition at line 100 of file WEPO41104A02.h.
eeprom_data* ptr_eeprom_sram_data
pointer to EEPROM image in SRAM
Definition at line 101 of file WEPO41104A02.h.