SPIKE 1.1: pal_trx_access.c File Reference
pal_trx_access.c File Reference
Transceiver registers & Buffer accessing functions for AVR 8-Bit SPI based MCUs.
#include <stdint.h>
#include "inc/at86.h"
#include "inc/pal_config.h"
#include <avr/io.h>
#include <inttypes.h>
#include <avr/Interrupt.h>
#include <avr/wdt.h>
#include <ctype.h>
#include <avr/sleep.h>
#include <util/delay.h>
Typedefs
typedef void(* spi_done_handler_t)(void)
Enumerations
enum spi_state_t { SPI_IDLE, SPI_READ, SPI_WRITE }
Functions
ISR (TRX_MAIN_ISR_VECTOR)
ISR for transceiver's main interrupt.
ISR (TRX_TSTAMP_ISR_VECTOR)
ISR for transceiver's RX TIME STAMP interrupt.
void pal_trx_aes_wrrd (uint8_t addr, uint8_t *idata, uint8_t length)
Writes and reads data into/from SRAM of the transceiver.
uint8_t pal_trx_bit_read (uint8_t addr, uint8_t mask, uint8_t pos)
SPI transfer ISR.
void pal_trx_bit_write (uint8_t reg_addr, uint8_t mask, uint8_t pos, uint8_t new_value)
Subregister write.
void pal_trx_frame_read (uint8_t *data, uint8_t length)
Reads frame buffer of the transceiver.
void pal_trx_frame_write (uint8_t *data, uint8_t length)
Writes data into frame buffer of the transceiver.
void pal_trx_irq_init (trx_irq_hdlr_idx_t trx_irq_num, void *trx_irq_cb)
Initializes the transceiver interrupts.
uint8_t pal_trx_reg_read (uint8_t addr)
Reads current value from a transceiver register.
void pal_trx_reg_write (uint8_t addr, uint8_t data)
SPI done callback initialization.
void pal_trx_sram_read (uint8_t addr, uint8_t *data, uint8_t length)
Reads data from SRAM of the transceiver.
void pal_trx_sram_write (uint8_t addr, uint8_t *data, uint8_t length)
Writes data into SRAM of the transceiver.
void trx_interface_init (void)
Initializes the transceiver interface.
Variables
static irq_handler_t irq_handler [NO_OF_TRX_IRQS]
Detailed Description
Transceiver registers & Buffer accessing functions for AVR 8-Bit SPI based MCUs.
This file implements functions for reading and writing transceiver registers and transceiver buffer for AVR 8-Bit SPI based MCUs. The decision whether to use the implementation within this file is based on the presence of the macro PAL_USE_SPI_TRX, to be defined in the respective board's pal_config.h. Absence of this macro implies the TAL for the respective board supplies its own implementation of this API.
Id:
pal_trx_access.c 16886 2009-07-31 14:04:55Z uwalter
Author
Atmel Corporation: http://www.atmel.com
Support email: avr@a.nosp@m.tmel.nosp@m..com
Definition in file pal_trx_access.c.
Typedef Documentation
typedef void(* spi_done_handler_t)(void)
This is a typedef of the function which is called from SPI end
Definition at line 46 of file pal_trx_access.c.
Enumeration Type Documentation
enum spi_state_t
Typdef SPI States
Enumerator
SPI_IDLE
SPI_READ
SPI_WRITE
Definition at line 51 of file pal_trx_access.c.
 {
     SPI_IDLE,
     SPI_READ,
     SPI_WRITE
 } spi_state_t;
Function Documentation
ISR (TRX_MAIN_ISR_VECTOR)
ISR for transceiver's main interrupt.
Definition at line 586 of file pal_trx_access.c.
References irq_handler, and TRX_MAIN_IRQ_HDLR_IDX.
 {
     irq_handler[TRX_MAIN_IRQ_HDLR_IDX]();
 }
ISR (TRX_TSTAMP_ISR_VECTOR)
ISR for transceiver's RX TIME STAMP interrupt.
Definition at line 595 of file pal_trx_access.c.
References irq_handler, and TRX_TSTAMP_IRQ_HDLR_IDX.
 {
     irq_handler[TRX_TSTAMP_IRQ_HDLR_IDX]();
 }
void pal_trx_aes_wrrd (uint8_t addr, uint8_t * idata, uint8_t length)
Writes and reads data into/from SRAM of the transceiver.
This function writes data into the SRAM of the transceiver and simultaneously reads the bytes.
Parameters
addr Start address in the SRAM for the write operation
idata Pointer to the data written/read into/from SRAM
length Number of bytes written/read into/from SRAM
Definition at line 474 of file pal_trx_access.c.
References ENTER_TRX_REGION, LEAVE_TRX_REGION, PAL_WAIT_500_NS, SPI_DUMMY_VALUE, SPI_IDLE, SPI_WAIT, SS_HIGH, SS_LOW, and TRX_CMD_SW.
 {
     uint8_t *odata;
     PAL_WAIT_500_NS();
     ENTER_TRX_REGION();
 #ifdef NON_BLOCKING_SPI
     while (spi_state != SPI_IDLE)
     {
         /* wait until SPI gets available */
     }
 #endif
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Send the command byte */
     SPDR0 = TRX_CMD_SW;
     SPI_WAIT();
     /* write SRAM start address */
     SPDR0 = addr;
     SPI_WAIT();
     /* now transfer data */
     odata = idata;
     /* write data byte 0 - the obtained value in SPDR0 is meaningless */
     SPDR0 = *idata++;
     SPI_WAIT();
     /* process data bytes 1...length-1: write and read */
     uint8_t itemp;  // use variable to accelerate SPI transfer
     SPDR0 = *idata++;
     length--;
     itemp = *idata;
     while (length > 0)
     {
         SPI_WAIT();
         *odata = SPDR0;
         SPDR0 = itemp;
         odata++;
         length--;
         idata++;
         itemp = *idata;
     }
     SPI_WAIT();
     /* to get the last data byte, write some dummy byte */
     SPDR0 = SPI_DUMMY_VALUE;
     SPI_WAIT();
     *odata = SPDR0;
     /* Stop the SPI transaction by setting SEL high */
     SS_HIGH();
     LEAVE_TRX_REGION();
 }
uint8_t pal_trx_bit_read (uint8_t addr, uint8_t mask, uint8_t pos)
SPI transfer ISR.
read specified bit from transceiver
This function handles the non-blocking SPI transfer. Subregister read
Parameters
addr offset of the register
mask bit mask of the subregister
pos bit position of the subregister
Returns
value of the read bit(s)
Definition at line 323 of file pal_trx_access.c.
References pal_trx_reg_read().
Referenced by at86rf231_change_channel(), at86rf231_change_channel_page(), at86rf231_change_tx_pwr(), at86rf231_init(), at86rf231_switch_pll_on(), at86rf231_tx_with_retry(), handle_received_frame_irq(), pm_config_protocol(), and trx_irq_handler_cb().
 {
     uint8_t ret;
     ret = pal_trx_reg_read(addr);
     ret &= mask;
     ret >>= pos;
     return ret;
 }
void pal_trx_bit_write (uint8_t reg_addr, uint8_t mask, uint8_t pos, uint8_t new_value)
Subregister write.
write specified bit to transceiver
Parameters
[in] reg_addr Offset of the register
[in] mask Bit mask of the subregister
[in] pos Bit position of the subregister
[out] new_value Data, which is muxed into the register
Definition at line 342 of file pal_trx_access.c.
References pal_trx_reg_read(), and pal_trx_reg_write().
Referenced by at86rf231_change_channel(), at86rf231_change_channel_page(), at86rf231_change_tx_pwr(), at86rf231_ftn_pll_calibration(), at86rf231_init(), and at86rf231_tx_with_retry().
 {
     uint8_t current_reg_value;
     current_reg_value = pal_trx_reg_read(reg_addr);
     current_reg_value &= ~mask;
     new_value <<= pos;
     new_value &= mask;
     new_value |= current_reg_value;
     pal_trx_reg_write(reg_addr, new_value);
 }
void pal_trx_frame_read (uint8_t * data, uint8_t length)
Reads frame buffer of the transceiver.
Upload frame from transceiver.
This function reads the frame buffer of the transceiver.
Parameters
[out] data Pointer to the location to store frame
[in] length Number of bytes to be read from the frame buffer.
Definition at line 199 of file pal_trx_access.c.
References SPI_DUMMY_VALUE, SPI_WAIT, SS_HIGH, SS_LOW, and TRX_CMD_FR.
Referenced by handle_received_frame_irq().
 {
     /* Assumption: This function is called within ISR. */
     cli();
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Send the command byte */
     SPDR0 = TRX_CMD_FR;
     SPI_WAIT();
     SPDR0 = SPI_DUMMY_VALUE;
     if (length != 1)
     {
         do
         {
             uint8_t temp;
             SPI_WAIT();
             /* Upload the received byte in the user provided location */
             temp = SPDR0;
             SPDR0 = SPI_DUMMY_VALUE; /* Do dummy write for initiating SPI read */
             *data = temp;
             data++;
             length--;
         } while (length > 1);
     }
     SPI_WAIT(); /* Wait until last bytes is transmitted. */
     *data = SPDR0;
     /* Stop the SPI transaction by setting SEL high */
     SS_HIGH();
     sei();
 }
void pal_trx_frame_write (uint8_t * data, uint8_t length)
Writes data into frame buffer of the transceiver.
write frame to transceiver
This function writes data into the frame buffer of the transceiver
Parameters
[in] data Pointer to data to be written into frame buffer
[in] length Number of bytes to be written into frame buffer
Definition at line 244 of file pal_trx_access.c.
References SPI_IRQ_ENABLE, SPI_WAIT, SPI_WRITE, SS_HIGH, SS_LOW, and TRX_CMD_FW.
Referenced by at86rf231_tx(), and at86rf231_tx_with_retry().
 {
 #ifndef NON_BLOCKING_SPI
     cli();
     /* Assumption: The TAL has already disabled the trx interrupt. */
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Start SPI transfer by sending the command byte */
     SPDR0 = TRX_CMD_FW;
     SPI_WAIT();
     do
     {
         uint8_t temp = *data;
         data++;
         length--;
         SPI_WAIT();
         SPDR0 = temp;
     } while (length > 0);
     SPI_WAIT(); /* Wait until last bytes is transmitted. */
     /* Stop the SPI transaction by setting SEL high */
     SS_HIGH();
     sei();
 #else
     spi_state = SPI_WRITE;
     spi_remaining_bytes = length;
     spi_data_ptr = data;
     SPI_IRQ_ENABLE();
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Start SPI transfer by sending the command byte */
     SPDR0 = TRX_CMD_FW;
 #endif
 }
void pal_trx_irq_init (trx_irq_hdlr_idx_t trx_irq_num, void * trx_irq_cb)
Initializes the transceiver interrupts.
init external interrupt
This function sets the microcontroller specific registers responsible for handling the transceiver interrupts
Parameters
trx_irq_num Transceiver interrupt line to be initialized
trx_irq_cb Callback function for the given transceiver interrupt
Definition at line 552 of file pal_trx_access.c.
References irq_handler, TRX_MAIN_IRQ_HDLR_IDX, and TRX_TSTAMP_IRQ_HDLR_IDX.
Referenced by at86rf231_init().
 {
     /*
      * Set the handler function.
      * The handler is set before enabling the interrupt to prepare for spurious
      * interrupts, that can pop up the moment they are enabled
      */
     irq_handler[trx_irq_num] = (irq_handler_t)trx_irq_cb;
     if (trx_irq_num == TRX_MAIN_IRQ_HDLR_IDX)
     {
         /* Init Main TRX interrupt */
         /* Select rising edge */
         EICRA |= _BV(ISC00) | _BV(ISC01);
         /* clear pending interrupt */
         EIFR = _BV(INTF0);
     }
 #ifndef ANTENNA_DIVERSITY
     else if (trx_irq_num == TRX_TSTAMP_IRQ_HDLR_IDX)
     {
         /* Init RX TIME STAMP interrupt */
         /* The input capture interrupt of timer is disabled */
         TIMSK1 &= ~(_BV(ICIE1));
         /* Rising edge on input capture pin used to trigger IRQ */
         TCCR1B |= (_BV(ICES1));
         /* Input capture flag is cleared */
         TIFR1 |= (_BV(ICF1));
     }
 #endif
 }
uint8_t pal_trx_reg_read (uint8_t addr)
Reads current value from a transceiver register.
read register from transceiver
This function reads the current value from a transceiver register.
Parameters
addr Specifies the address of the trx register from which the data shall be read
Returns
value of the register read
Definition at line 149 of file pal_trx_access.c.
References ENTER_TRX_REGION, LEAVE_TRX_REGION, READ_ACCESS_COMMAND, SPI_DUMMY_VALUE, SPI_IDLE, SPI_WAIT, SS_HIGH, and SS_LOW.
Referenced by at86rf231_init(), at86rf231_switch_pll_on(), handle_received_frame_irq(), pal_trx_bit_read(), pal_trx_bit_write(), and trx_irq_handler_cb().
 {
     uint8_t register_value;
     cli();
     ENTER_TRX_REGION();
 #ifdef NON_BLOCKING_SPI
     while (spi_state != SPI_IDLE)
     {
         /* wait until SPI gets available */
     }
 #endif
     /* Prepare the command byte */
     addr |= READ_ACCESS_COMMAND;
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Send the Read command byte */
     SPDR0 = addr;
     SPI_WAIT();
     /* Do dummy read for initiating SPI read */
     SPDR0 = SPI_DUMMY_VALUE;
     SPI_WAIT();
     /* Read the byte received */
     register_value = SPDR0;
     /* Stop the SPI transaction by setting SEL high */
     SS_HIGH();
     LEAVE_TRX_REGION();
     sei();
     return register_value;
 }
void pal_trx_reg_write (uint8_t addr, uint8_t data)
SPI done callback initialization.
write register to transceiver
Writes data into a transceiver register
This function writes a value into transceiver register.
Parameters
addr Address of the trx register
data Data to be written to trx register
Definition at line 106 of file pal_trx_access.c.
References ENTER_TRX_REGION, LEAVE_TRX_REGION, SPI_IDLE, SPI_WAIT, SS_HIGH, SS_LOW, and WRITE_ACCESS_COMMAND.
Referenced by at86rf231_change_channel(), at86rf231_change_channel_page(), at86rf231_change_tx_pwr(), at86rf231_ftn_pll_calibration(), at86rf231_init(), at86rf231_rx_with_auto_ack(), at86rf231_sleep(), at86rf231_switch_pll_on(), at86rf231_tx(), at86rf231_tx_with_retry(), handle_received_frame_irq(), pal_trx_bit_write(), pm_config_protocol(), and trx_irq_handler_cb().
 {
     cli();
     ENTER_TRX_REGION();
 #ifdef NON_BLOCKING_SPI
     while (spi_state != SPI_IDLE)
     {
         /* wait until SPI gets available */
     }
 #endif
     /* Prepare the command byte */
     addr |= WRITE_ACCESS_COMMAND;
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Send the Read command byte */
     SPDR0 = addr;
     SPI_WAIT();
     /* Write the byte in the transceiver data register */
     SPDR0 = data;
     SPI_WAIT();
     /* Stop the SPI transaction by setting SEL high */
     SS_HIGH();
     LEAVE_TRX_REGION();
     sei();
 }
void pal_trx_sram_read (uint8_t addr, uint8_t * data, uint8_t length)
Reads data from SRAM of the transceiver.
This function reads from the SRAM of the transceiver
Parameters
[in] addr Start address in SRAM for read operation
[out] data Pointer to the location where data stored
[in] length Number of bytes to be read from SRAM
Definition at line 415 of file pal_trx_access.c.
References ENTER_TRX_REGION, LEAVE_TRX_REGION, PAL_WAIT_500_NS, SPI_DUMMY_VALUE, SPI_IDLE, SPI_WAIT, SS_HIGH, SS_LOW, and TRX_CMD_SR.
 {
     PAL_WAIT_500_NS();
     ENTER_TRX_REGION();
 #ifdef NON_BLOCKING_SPI
     while (spi_state != SPI_IDLE)
     {
         /* wait until SPI gets available */
     }
 #endif
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Send the command byte */
     SPDR0 = TRX_CMD_SR;
     SPI_WAIT();
     /* Send the address from which the read operation should start */
     SPDR0 = addr;
     SPI_WAIT();
     SPDR0 = SPI_DUMMY_VALUE;
     length--;
     while (length > 0)
     {
         uint8_t temp;
         SPI_WAIT();
         /* Upload the received byte in the user provided location */
         temp =  SPDR0;
         SPDR0 = SPI_DUMMY_VALUE; /* Do dummy write for initiating SPI read */
         *data++ = temp;
         length--;
     }
     SPI_WAIT(); /* Wait until last bytes is transmitted. */
     *data++ = SPDR0; // read last data byte
     SS_HIGH();
     LEAVE_TRX_REGION();
 }
void pal_trx_sram_write (uint8_t addr, uint8_t * data, uint8_t length)
Writes data into SRAM of the transceiver.
This function writes data into the SRAM of the transceiver
Parameters
addr Start address in the SRAM for the write operation
data Pointer to the data to be written into SRAM
length Number of bytes to be written into SRAM
Definition at line 365 of file pal_trx_access.c.
References ENTER_TRX_REGION, LEAVE_TRX_REGION, SPI_IDLE, SPI_WAIT, SS_HIGH, SS_LOW, and TRX_CMD_SW.
 {
     ENTER_TRX_REGION();
 #ifdef NON_BLOCKING_SPI
     while (spi_state != SPI_IDLE)
     {
         /* wait until SPI gets available */
     }
 #endif
     /* Start SPI transaction by pulling SEL low */
     SS_LOW();
     /* Send the command byte */
     SPDR0 = TRX_CMD_SW;
     SPI_WAIT();
     /* Send the address from which the write operation should start */
     SPDR0 = addr;
     SPI_WAIT();
     do
     {
         uint8_t temp = *data;
         data++;
         length--;
         SPI_WAIT();
         SPDR0 = temp;
     } while (length > 0);
     SPI_WAIT(); /* Wait until last bytes is transmitted. */
     /* Stop the SPI transaction by setting SEL high */
     SS_HIGH();
     LEAVE_TRX_REGION();
 }
void trx_interface_init (void)
Initializes the transceiver interface.
init spi interace
This function initializes the transceiver interface.
Definition at line 82 of file pal_trx_access.c.
References TRX_INIT.
Referenced by at86rf231_init().
 {
     TRX_INIT();
 }
Variable Documentation
irq_handler_t irq_handler[NO_OF_TRX_IRQS] static
Definition at line 62 of file pal_trx_access.c.
Referenced by ISR(), and pal_trx_irq_init().