SPIKE 1.1: WEPO41104A02.h File Reference
WEPO41104A02.h File Reference
Main header of the program.
#include <avr/io.h>
#include <inttypes.h>
#include <avr/Interrupt.h>
#include <ctype.h>
#include <avr/sleep.h>
#include <util/delay.h>
#include <avr/signature.h>
#include "eeprom_abbild.h"
#include "SX8723c.h"
#include "ds620.h"
#include "at86.h"
#include "SPIKE_config.h"
#include "pm_config_protocol.h"
#include "conf_LED.h"
#include "fuses.h"
Macros
#define BATTERY_THRESHOLD_EMPTY 171
threshold = battery empty (digit)
#define F_CPU 10000000
CPU clock (in Hz)
#define SG_1 0
number of the first strain gauge
#define SG_2 1
number of the secound strain gauge
#define SG_3 2
number of the third strain gauge
#define SG_4 3
number of the fourth strain gauge
Enumerations
enum state_t {
STATE_INIT = 0x00, STATE_SLEEP = 0x01, STATE_WAKE_UP = 0x02, STATE_MEASUREMENT_PREPARE = 0x03,
STATE_MEASUREMENT = 0x04, STATE_MEASUREMENT_CLOSE = 0x05, STATE_SEND = 0x06, STATE_CONFIG = 0x07
}
A structure to present the states of the finite state machine.
Functions
void avr_init (void)
Initialization of the controller and all sensors.
void init_adc (void)
Initialized the ADC.
ISR (TIMER1_COMPA_vect)
Interrupt handler of the timer/counter 1.
ISR (ANALOG_COMP_vect)
Interrupt handler of the analog comparator.
int main (void)
Main function.
static void send_all_data_rf231 (void)
Function to send a data packet.
void set_sleep (void)
Set micro controller to sleep mode.
void timer_init (void)
Initialized the timer/counter 1.
Variables
volatile at86rf231_frame at86rf231_rx_frame
global receive buffer for the AT86RF231
volatile at86rf231_frame at86rf231_tx_frame
global transmit buffer for the AT86RF231
volatile state_t current_state = 0x00
current state of the state machine
eeprom_data eeprom_sram_data = { 0 }
EEPROM image in SRAM.
eeprom_data * ptr_eeprom_sram_data = &eeprom_sram_data
pointer to EEPROM image in SRAM
spike_payload * ptr_payload_spike = (spike_payload*) at86rf231_tx_frame.payload
pointer to payload
volatile bool stop_stream = 0
flag to stop sending data
tal_state_t tal_state
Transceiver states.
volatile int16_t temperature = 0
measurement value of the temperature sensor
uint16_t temperature_timer = 0
timer for next measurement
uint32_t timeout_timer = 0
timeout timer to switch into sleep mode
volatile uint8_t timer_flag = 0
flag = 1 if timer interrupt occurred
uint8_t timeslot_number = 0
time slot number in transmitted payload
volatile uint8_t tx_end_irq_flag
Transmit interrupt flag = 1 transmission completed.
volatile uint8_t use_acceleration_sensor_flag = 1
turn acceleration measurement on if flag = 1
Detailed Description
Main header of the program.
Functional description:
Target Platforms: ATmega324P
Editor: Atmel AVR Studio 5 (Version: 5.1.208)
Compiler: AVRGCC (Version: 3.3.1.27)
Date
2013-09-05
Version
WEPO41104A02
Author
created by flm, mih, job, ank
Copyright ©2013 pro-micron GmbH & Co. KG, All rights reserved.
Definition in file WEPO41104A02.h.
Macro Definition Documentation
#define BATTERY_THRESHOLD_EMPTY 171
threshold = battery empty (digit)
Definition at line 58 of file WEPO41104A02.h.
Referenced by main().
#define F_CPU 10000000
CPU clock (in Hz)
Definition at line 25 of file WEPO41104A02.h.
#define SG_1 0
number of the first strain gauge
Definition at line 53 of file WEPO41104A02.h.
Referenced by main().
#define SG_2 1
number of the secound strain gauge
Definition at line 54 of file WEPO41104A02.h.
Referenced by main().
#define SG_3 2
number of the third strain gauge
Definition at line 55 of file WEPO41104A02.h.
Referenced by main().
#define SG_4 3
number of the fourth strain gauge
Definition at line 56 of file WEPO41104A02.h.
Referenced by main().
Enumeration Type Documentation
enum state_t
A structure to present the states of the finite state machine.
Enumerator
STATE_INIT
State initzialization.
STATE_SLEEP
State sleep.
STATE_WAKE_UP
State wake up from sleet.
STATE_MEASUREMENT_PREPARE
State measurement prepare.
STATE_MEASUREMENT
State do measurement.
STATE_MEASUREMENT_CLOSE
State measurement close.
STATE_SEND
State send payload.
STATE_CONFIG
State get configuration.
Definition at line 65 of file WEPO41104A02.h.
             {
     STATE_INIT                  =   0x00,
     STATE_SLEEP                 =   0x01,
     STATE_WAKE_UP               =   0x02,
     STATE_MEASUREMENT_PREPARE   =   0x03,
     STATE_MEASUREMENT           =   0x04,
     STATE_MEASUREMENT_CLOSE     =   0x05,
     STATE_SEND                  =   0x06,
     STATE_CONFIG                =   0x07
 }state_t;
Function Documentation
void avr_init (void)
Initialization of the controller and all sensors.
Definition at line 509 of file WEPO41104A02.c.
References at86rf231_init(), device_1, device_2, device_3, device_4, ds620_init(), eeprom_read_config(), eeprom_sram_data, init_adc(), INIT_LED, ptr_eeprom_sram_data, SX8723c_init(), eeprom_data::timeout, timer_init(), and use_acceleration_sensor_flag.
Referenced by main().
 {
     MCUCR &= ~(1 << PUD);   // enable internal pull ups
     PRR0 = 0x00;            // power manager: enable all modules
     CLKPR = 0x80;           // Set system clock prescaler
     CLKPR = 0x00;           // prescaler to 1
     DDRA = 0x00;
     PORTA = 0x1F;
     DDRB = 0xB1;
     PORTB = 0x50;
     DDRC = 0xC0;
     PORTC = 0x80;
     DDRD = (1 << PIND4) | (1 << PIND7);     // 1 = output, 0 = input
     PORTD = (1 << PIND4) | ( 1 << PIND7);   // 1 = high, 0 = low
     INIT_LED;               // initialize LED
     eeprom_read_config(ptr_eeprom_sram_data);   // store EEPROM data to SRAM (faster access)
     // if timeout = 0 --> deactivate acceleration sensor, always on
     if (eeprom_sram_data.timeout == 0)
     {
         use_acceleration_sensor_flag = 0;
     }
     else
     {
         use_acceleration_sensor_flag = 1;
     }
 #if defined(USE_DS620)
     ds620_init();       // initialize temperature sensor
 #endif
     ACSR = 0x82;        // analog-comparator off, comparator Interrupt on Falling Output Edge
     timer_init();       // timer initialization
     init_adc();         // ADC initialization
     at86rf231_init();   // AT86RF231 initialization
     _delay_ms(10);      // Wait until SX8723c is ready to communicate (start up time)
     SX8723c_init(device_1);     // SX8723c initialization (bridge 1)
     SX8723c_init(device_2);     // SX8723c initialization (bridge 2)
     SX8723c_init(device_3);     // SX8723c initialization (bridge 3)
     SX8723c_init(device_4);     // SX8723c initialization (bridge 4)
 }
void init_adc (void)
Initialized the ADC.
Definition at line 564 of file WEPO41104A02.c.
Referenced by avr_init(), and main().
 {
     // ADC Multiplexer Selection Register
     ADMUX = (1 << REFS1) | (1 << ADLAR) | (1 << MUX0) | (1 << MUX1) | (1 << MUX2);      // ADC7, Left Adjust, 1.1V Ref
     // ADC Control and Status Register A
     ADCSRA = (1 << ADSC) | (1 << ADATE) | (1 << ADEN) | (1 << ADPS2) | (1 << ADPS0);    // ADC enable, Start conversion, AutoTrigger enable, Prescaler: 32
     // ADC Control and Status Register B
     ADCSRB = 0;             // Free Running mode
 }
ISR (TIMER1_COMPA_vect)
Interrupt handler of the timer/counter 1.
Definition at line 634 of file WEPO41104A02.c.
References timer_flag.
 {
     timer_flag = 1; // set timer flag
 }
ISR (ANALOG_COMP_vect)
Interrupt handler of the analog comparator.
Definition at line 639 of file WEPO41104A02.c.
 {
     ACSR = 0x12; // analog-comparator on, interrupt off, clear interrupt
 }
int main (void)
Main function.
Definition at line 241 of file WEPO41104A02.c.
References at86rf231_rx_frame, at86rf231_sleep(), avr_init(), BATTERY_THRESHOLD_EMPTY, current_state, device_all, ds620_get_temperature(), ds620_start_convert(), ds620_stop_convert(), eeprom_sram_data, init_adc(), LED_OFF, LED_ON, at86rf231_frame::payload, pm_config_protocol(), ptr_eeprom_sram_data, ptr_payload_spike, eeprom_data::samplerate, SAMPLES_PER_PACKET, send_all_data_rf231(), set_sleep(), SG_1, SG_2, SG_3, SG_4, eeprom_data::SG_software_offset, STATE_CONFIG, STATE_INIT, STATE_MEASUREMENT, STATE_MEASUREMENT_CLOSE, STATE_MEASUREMENT_PREPARE, STATE_SEND, STATE_SLEEP, STATE_WAKE_UP, stop_stream, spike_payload::strain_gauge, SX8723c_get_value(), SX8723c_send_request(), SX8723c_sleep(), SX8723c_start(), temperature, temperature_timer, eeprom_data::timeout, timeout_timer, timer_flag, timeslot_number, and use_acceleration_sensor_flag.
 {
     cli();                              // clear interrupt
     avr_init();                         // controller and sensor initialization
     int16_t SG_value[4] = {0};          // value of the strain gauges
     int16_t *p_SG_value = SG_value;     // pointer to value
     current_state = STATE_INIT;         // set current state
     /*--------------- State Machine ----------------------------------------------*/
     while(1)
     {
         switch(current_state)
         {
             /*---------------- INIT ----------------*/
             case STATE_INIT:
                 TCCR1B = 0x00;  // stop timer; TODO ntig?
                 TIFR1 = 0x02;   // Output Compare A Match Flag reset; TODO ntig?
                 // SX8723c and strain gauges off
                 SX8723c_sleep(device_all);
                 #if defined(USE_DS620)
                     // temperature sensor off
                     ds620_stop_convert();
                 #endif
                 // ADC off
                 ADCSRA = 0x00;
                 // Transceiver in Power-down
                 at86rf231_sleep();
                 current_state = STATE_SLEEP;
             break;
             /*---------------- SLEEP ----------------*/
             case STATE_SLEEP:
                 set_sleep();
                 current_state = STATE_WAKE_UP;
             break;
             /*---------------- WAKE_UP ----------------*/
             case STATE_WAKE_UP:
                 // charging?
                 if (PIND & 0x20)
                 {
                     current_state = STATE_SLEEP;
                     break;
                 }
                 // power reduction register
                 PRR0 = 0x00;    // enable all modules
                 // battery empty?
                 init_adc();
                 _delay_ms(1);
                 if (ADCH <= (BATTERY_THRESHOLD_EMPTY+2) ) // +2 hysteresis
                 {
                     current_state = STATE_SLEEP;
                     break;
                 }
                 // Set system clock prescaler
                 CLKPR = 0x80;
                 CLKPR = 0x00;   // prescaler = 1
                 current_state = STATE_MEASUREMENT_PREPARE;
             break;
             /*---------------- MEASUREMENT_PREPARE ----------------*/
             case STATE_MEASUREMENT_PREPARE:
                 cli();
                 #if defined(USE_DS620)
                     ds620_start_convert();
                 #endif
                 // Start SX8723c an turn strain gauge power on
                 SX8723c_start(device_all);
                 // reset time_slot to avoid sending old data
                 timeslot_number = 0;
                 timeout_timer = 0;
                 // start timer
                 TCCR1B = 0x09;  // CTC, no prescaler
                 TIFR1 = 0x02;   // clear output compare a match flag
                 sei();
                 current_state = STATE_MEASUREMENT;
             break;
             /*---------------- MEASUREMENT ----------------*/
             case STATE_MEASUREMENT:
                 if (timer_flag)
                 {
                     timer_flag = 0;
                     // increase timeout_timer
                     timeout_timer++;
                     #if defined(USE_DS620)
                     // increase temperature timer
                     temperature_timer++;
                     #endif
                     LED_ON;                                         // turn LED ON
                     SX8723c_send_request(device_all);               // Send request to all bridges
                     SX8723c_get_value(device_all, p_SG_value);      // Read data from all bridges
                     LED_OFF;                                        // turn LED of
                     // store data in payload
                     ptr_payload_spike->strain_gauge[timeslot_number][SG_1] = SG_value[SG_1] - ptr_eeprom_sram_data->SG_software_offset[SG_1];
                     ptr_payload_spike->strain_gauge[timeslot_number][SG_2] = SG_value[SG_2] - ptr_eeprom_sram_data->SG_software_offset[SG_2];
                     ptr_payload_spike->strain_gauge[timeslot_number][SG_3] = SG_value[SG_3] - ptr_eeprom_sram_data->SG_software_offset[SG_3];
                     ptr_payload_spike->strain_gauge[timeslot_number][SG_4] = SG_value[SG_4] - ptr_eeprom_sram_data->SG_software_offset[SG_4];
                     // Time slot++
                     timeslot_number++;
                     #if defined(USE_DS620)
                     // get temperature value if 200ms over and time slot number is 3
                     if( (temperature_timer >= (eeprom_sram_data.samplerate / 5)) & (timeslot_number == 3))
                     {
                         temperature = ds620_get_temperature();
                         temperature_timer = 0;
                     }
                     #endif
                     // send data with radio if necessary
                     if (timeslot_number >= SAMPLES_PER_PACKET)
                     {
                         timeslot_number = 0;
                         current_state = STATE_SEND;
                         break;
                     }
                 }
                 // Acceleration about threshold: reset timeout_timer
                 if ((use_acceleration_sensor_flag == 1) && (!(ACSR & 0x20)))
                 {
                     timeout_timer = 0;
                 }
                 current_state = STATE_MEASUREMENT;
             break;
             /*---------------- MEASUREMENT_CLOSE ----------------*/
             case STATE_MEASUREMENT_CLOSE:
                 TCCR1B = 0x00;  // stop timer
                 TIFR1 = 0x02;   // Output Compare A Match Flag reset
                 // SX8723c and strain gauge off
                 SX8723c_sleep(device_all);
                 #if defined(USE_DS620)
                     // temperature sensor off
                     ds620_stop_convert();
                 #endif
                 // ADC off
                 ADCSRA = 0x00;
                 // Transceiver in Power-down
                 at86rf231_sleep();
                 current_state = STATE_SLEEP;
             break;
             /*---------------- SEND ----------------*/
             case STATE_SEND:
                 // send data
                 send_all_data_rf231();
                 // Received an configuration packet?
                 if ( at86rf231_rx_frame.payload[0] != 0x00 )
                 {
                     current_state = STATE_CONFIG;
                     break;
                 }
                 // charging?
                 if (PIND & 0x20)
                 {
                     current_state = STATE_MEASUREMENT_CLOSE;
                     break;
                 }
                 // timeout occurred?
                 if ((timeout_timer > (unsigned long) eeprom_sram_data.timeout * eeprom_sram_data.samplerate) && use_acceleration_sensor_flag)
                 {
                     timeout_timer = 0;
                     current_state = STATE_MEASUREMENT_CLOSE;
                     break;
                 }
                 // battery empty?
                 if (ADCH <= BATTERY_THRESHOLD_EMPTY)
                 {
                     current_state = STATE_MEASUREMENT_CLOSE;
                     break;
                 }
                 // stop sending data?
                 if (stop_stream)
                 {
                     stop_stream = 0;
                     current_state = STATE_MEASUREMENT_CLOSE;
                     break;
                 }
                 current_state = STATE_MEASUREMENT;
             break;
             /*---------------- CONFIG ----------------*/
             case STATE_CONFIG:
                 _delay_ms(40);
                 /* Receive and process data */
                 pm_config_protocol();
                 current_state = STATE_MEASUREMENT;
             break;
             /*---------------- default ----------------*/
             default:
             break;
         }
     }
 }
static void send_all_data_rf231 (void) inline static
Function to send a data packet.
void set_sleep (void)
Set micro controller to sleep mode.
Definition at line 576 of file WEPO41104A02.c.
Referenced by main().
 {
     cli();
     // change clock prescaler
     CLKPR = 0x80;   // Clock Prescaler Change Enable
     CLKPR = 0x03;   // Prescaler = 8
     // power reduction register
     PRR0 = 0xFE;
     // analog-comparator on, interrupt on falling edge
     ACSR = 0x1A;
     // set CPU sleep
     set_sleep_mode(SLEEP_MODE_IDLE);
     sleep_enable();
     sei();
     sleep_cpu();
     sleep_disable();
 }
void timer_init (void)
Initialized the timer/counter 1.
The timer generates the timing for the measurement.
Definition at line 491 of file WEPO41104A02.c.
References eeprom_sram_data, F_CPU, and eeprom_data::samplerate.
Referenced by avr_init().
 {
     // timer/counter1
     TCCR1A = 0x00; // Timer/Counter1 Control Register
     TCCR1B = 0x09; // Clear Timer on Compare match (CTC); No clock source (Timer/Counter stopped)
     // Output Compare Register 1 A
     OCR1A = (unsigned short) ((float) F_CPU
             / (float) eeprom_sram_data.samplerate); // set timer to sample rate
     TCNT1 = 0x0000;         // set counter to null
     OCR1B = 0x0000;         //  Output Compare Register 1 B
     ICR1 = 0x0000;          // Input Capture Register 1
     TIMSK1 = 1 << OCIE1A;   // Timer/Counter1 Interrupt Mask Register; Output Compare A Match, interrupt enable
     TIFR1 = 0x02;           // Timer/Counter1 Interrupt Flag Register; clear output compare a match flag
 }
Variable Documentation
volatile at86rf231_frame at86rf231_rx_frame
global receive buffer for the AT86RF231
Definition at line 22 of file at86rf231.c.
Referenced by main(), and pm_config_protocol().
volatile at86rf231_frame at86rf231_tx_frame
global transmit buffer for the AT86RF231
Definition at line 21 of file at86rf231.c.
Referenced by pm_config_protocol(), and send_all_data_rf231().
volatile state_t current_state = 0x00
current state of the state machine
Definition at line 96 of file WEPO41104A02.h.
Referenced by main().
spike_payload* ptr_payload_spike = (spike_payload*) at86rf231_tx_frame.payload
pointer to payload
Definition at line 98 of file WEPO41104A02.h.
Referenced by main(), and send_all_data_rf231().
volatile bool stop_stream = 0
flag to stop sending data
Definition at line 90 of file WEPO41104A02.h.
Referenced by main(), and pm_config_protocol().
tal_state_t tal_state
Transceiver states.
Definition at line 24 of file at86rf231.c.
Referenced by at86rf231_init(), at86rf231_rx_with_auto_ack(), at86rf231_tx(), at86rf231_tx_with_retry(), and trx_irq_handler_cb().
volatile int16_t temperature = 0
measurement value of the temperature sensor
Definition at line 89 of file WEPO41104A02.h.
Referenced by main(), and send_all_data_rf231().
uint16_t temperature_timer = 0
timer for next measurement
Definition at line 93 of file WEPO41104A02.h.
Referenced by main().
uint32_t timeout_timer = 0
timeout timer to switch into sleep mode
Definition at line 85 of file WEPO41104A02.h.
Referenced by main(), and pm_config_protocol().
volatile uint8_t timer_flag = 0
flag = 1 if timer interrupt occurred
Definition at line 88 of file WEPO41104A02.h.
Referenced by ISR(), and main().
uint8_t timeslot_number = 0
time slot number in transmitted payload
Definition at line 86 of file WEPO41104A02.h.
Referenced by main().
volatile uint8_t tx_end_irq_flag
Transmit interrupt flag = 1 transmission completed.
Definition at line 25 of file at86rf231.c.
Referenced by at86rf231_tx(), at86rf231_tx_with_retry(), and trx_irq_handler_cb().
volatile uint8_t use_acceleration_sensor_flag = 1
turn acceleration measurement on if flag = 1
Definition at line 87 of file WEPO41104A02.h.
Referenced by avr_init(), main(), and pm_config_protocol().