SPIKE 1.1: WEPO41104A00.h File Reference
WEPO41104A00.h File Reference
#include <avr/io.h>
#include <inttypes.h>
#include <avr/Interrupt.h>
#include <avr/wdt.h>
#include <ctype.h>
#include <avr/sleep.h>
#include <util/delay.h>
#include "eeprom_abbild.h"
#include "SX8723c.h"
#include "ds620.h"
#include "at86.h"
#include "SPIKE_config.h"
#include "pm_config_protocol.h"
#include "conf_LED.h"
Defines
#define F_CPU 10000000
#define SG_1 0
#define SG_2 1
#define SG_3 2
#define SG_4 3
Functions
void avr_init (void)
Grundlegende initialisierungen des Controlers und der Peripherie.
void init_adc (void)
void init_wdt (void)
ISR (TIMER1_COMPA_vect)
Timerinterrupt, wird SAPLERATE mal in der Sekunde ausgeführt.
ISR (ANALOG_COMP_vect)
Interrupt des analog-Komperators, wird ausgeführt, wenn die Radialbeschleunigung über 2g steigt.
ISR (WDT_vect)
int main (void)
Hauptroutine.
static void send_all_data_rf231 (void)
sendet ein Datenpacket
void set_sleep (void)
Routine zum Eintritt in den Standby-Modus.
void start (void)
Startroutine zum Verlassen des Standby-Modus.
void timer_init (void)
Initialisiert den Timer1 auf Interrupt im Intervall der Samplerate.
Define Documentation
#define F_CPU 10000000
Definition at line 13 of file WEPO41104A00.h.
#define SG_1 0
Definition at line 36 of file WEPO41104A00.h.
Referenced by main().
#define SG_2 1
Definition at line 37 of file WEPO41104A00.h.
Referenced by main().
#define SG_3 2
Definition at line 38 of file WEPO41104A00.h.
Referenced by main().
#define SG_4 3
Definition at line 39 of file WEPO41104A00.h.
Referenced by main().
Function Documentation
void avr_init (void)
Grundlegende initialisierungen des Controlers und der Peripherie.
Definition at line 396 of file WEPO41104A00.c.
References at86rf231_init(), besch_start_flag, device_1, device_2, device_3, device_4, ds620_twi_init(), eeprom_read_config(), eeprom_sram_data, init_adc(), INIT_LED, SX8723c_init(), eeprom_data::timeout, and timer_init().
Referenced by main().
{
    MCUCR &= ~(1 << PUD);   // enable internal pull ups
    PRR0 = 0x00;        // power manager: enable all modules
    /* Set system clock prescaler */
    CLKPR = 0x80;
    CLKPR = 0x00; // prescaler to 1
    DDRA = 0x00;
    PORTA = 0x1F;
    DDRB = 0xB1;
    PORTB = 0x50;
    DDRC = 0xC0;
    PORTC = 0x80;
    DDRD = (1 << PIND4) | (1 << PIND7);     // 1 = output, 0 = input
    PORTD = (1 << PIND4) | ( 1 << PIND7);   // 1 = high, 0 = low
    INIT_LED;
    DDRB |= (1 << PINB4); // ank debug
    PORTB &= ~(1 << PINB4); // (für Debugzwecke) ank
    eeprom_read_config(ptr_eeprom_sram_data);   // store EEPROM data to SRAM (faster access)
    /* if timeout = 0 --> deaktivate acceleration sensor, always on */
    if (eeprom_sram_data.timeout == 0)
    {
        besch_start_flag = 0;
    }
    else
    {
        besch_start_flag = 1;
    }
#if defined(USE_DS620)
    ds620_twi_init();
#endif
    SX8723c_init(device_1);
    SX8723c_init(device_2);
    SX8723c_init(device_3);
    SX8723c_init(device_4);
    ACSR = 0x82; // analog-comparator off, comparator Interrupt on Falling Output Edge
    timer_init(); // timer initialization
    /* adc init */
    init_adc();
    at86rf231_init();   // AT86RF231 initialization
}
void init_adc (void)
Definition at line 453 of file WEPO41104A00.c.
Referenced by avr_init(), and start().
{
    ADMUX = (1 << REFS1) | (1 << ADLAR) | (1 << MUX0) | (1 << MUX1) | (1
            << MUX2); // ADC7, Left Adjust, 1.1V Ref
    ADCSRA = (1 << ADSC) | (1 << ADATE) | (1 << ADEN) | (1 << ADPS2) | (1
            << ADPS0); // ADC enable, Start conversion, AutoTrigger enable, Prescaler: 32
    ADCSRB = 0;
}
void init_wdt (void)
Definition at line 375 of file WEPO41104A00.c.
{
    //WDTCSR |= (1 << WDCE) | (1 << WDE);       // watchdog enable
    WDTCSR |= ((1 << WDCE) | (1 << WDIE));      // watchdog enable
    WDTCSR = 0x29;                          // Watchdog 8s, reset-mode
    wdt_reset();
}
ISR (TIMER1_COMPA_vect)
Timerinterrupt, wird SAPLERATE mal in der Sekunde ausgeführt.
Definition at line 579 of file WEPO41104A00.c.
References timer_flag.
{
    DDRA |= (1 << PIND6);
    PORTA |= (1 << PIND6); // TXD auf 0 (für Debugzwecke) ank
    /* Reset timer flag */
    timer_flag = 1;
    //sw_TWI_write_single_register(0x0F, 0x40, 0x55);   //ank
    //sw_TWI_read_value_registers(0x0F, p_test);    //ank
    PORTA &= ~(1 << PIND6); // TXD auf 0 (für Debugzwecke) ank
}
ISR (ANALOG_COMP_vect)
Interrupt des analog-Komperators, wird ausgeführt, wenn die Radialbeschleunigung über 2g steigt.
Definition at line 594 of file WEPO41104A00.c.
References start().
{
    /* Spike is not charging */
    if( !(PIND&0x20) )
    {
        /* start measuring */
        start();
    }
    else
    {
        /* sleep again if spike is already charging */
        ACSR = 0x1A; // analog-Komperator an, Interrupt bei fallender Flanke
        set_sleep_mode(SLEEP_MODE_IDLE);
        wdt_reset();        //ank
        sleep_enable();
        sei();
        sleep_cpu(); // IDLE-Modus
        sleep_disable();
    }
}
ISR (WDT_vect)
Definition at line 616 of file WEPO41104A00.c.
References wdt_interrupt_occurred.
{
    wdt_interrupt_occurred = true;
}
int main (void)
Hauptroutine.
Definition at line 246 of file WEPO41104A00.c.
References avr_init(), besch_start_flag, device_all, ds620_get_temperature(), eeprom_sram_data, LED_OFF, LED_ON, at86rf231_frame::payload, pm_config_protocol(), eeprom_data::samplerate, SAMPLES_PER_PACKET, send_all_data_rf231(), set_sleep(), SG_1, SG_2, SG_3, SG_4, eeprom_data::SG_software_offset, start(), spike_payload::strain_gauge, SX8723c_get_value(), SX8723c_send_request(), temperature, temperature_timer, eeprom_data::timeout, timeout_timer, timer_flag, and timeslot_number.
{
    cli();          // clear interrupt
    // TODO remove or edit
    //init_wdt();       // watchdog initialization
    //init_wdt_int();
    avr_init();     // controller initialization
    int16_t SG_value[4] = {0};
    int16_t *p_SG_value = SG_value;
    /* Use acceleration sensor? */
    if (besch_start_flag)
    {
        if (!(ACSR & 0x20))
            set_sleep();    // radial acceleration under threshold --> sleep
        else
            start();        // radial acceleration over threshold --> start measurment
    }
    else
    {
        if ( !(PIND & 0x20))
            start();        // Spike is not charging --> start measurment
        else
            set_sleep();    // Spike is charging --> sleep
    }
    /* ------------------ LOOP FOREVER ------------------------- */
    for (;;)
    {
        /* REQ_CFG CMD received? */
        if (at86rf231_rx_frame.payload[0] != 0x00)
        {
            /* Reset CMD */
            //at86rf231_rx_frame.payload[0] = 0x00;
            _delay_ms(40);
            /* Receive and process data */
            pm_config_protocol();
        }
        /* If spike is charging --> sleep mode */
        if (PIND & 0x20)
        {
            set_sleep();
        }
        /* timeout occurred --> sleep mode */
        if ((timeout_timer > (unsigned long) eeprom_sram_data.timeout * eeprom_sram_data.samplerate) && besch_start_flag)
        {
            timeout_timer = 0;
            set_sleep();
        }
        /* Radialbeschleunigung vorhanden: timeout_timer zurücksetzten */
        if ((besch_start_flag == 1) && (!(ACSR & 0x20)))
        {
            timeout_timer = 0;
        }
        if (timer_flag)
        {
            timer_flag = 0;
            /* increase timeout_timer */
            timeout_timer++;
            #if defined(USE_DS620)
            // increase temperature timer
            temperature_timer++;
            #endif
            LED_ON;
            /* Read data from Sx8723c 1-4 */
            SX8723c_send_request(device_all);   // TODO wieder anschalten
            //DDRB |= (1 << PINB4); // ank
            //PORTB |= (1 << PINB4); // (für Debugzwecke) ank
            SX8723c_get_value(device_all, p_SG_value);
            //PORTB &= ~(1 << PINB4); // (für Debugzwecke) ank
            LED_OFF;
            /* store data in payload */
            ptr_payload_spike->strain_gauge[timeslot_number][SG_1] = SG_value[SG_1] - ptr_eeprom_sram_data->SG_software_offset[SG_1];
            ptr_payload_spike->strain_gauge[timeslot_number][SG_2] = SG_value[SG_2] - ptr_eeprom_sram_data->SG_software_offset[SG_2];
            ptr_payload_spike->strain_gauge[timeslot_number][SG_3] = SG_value[SG_3] - ptr_eeprom_sram_data->SG_software_offset[SG_3];
            ptr_payload_spike->strain_gauge[timeslot_number][SG_4] = SG_value[SG_4] - ptr_eeprom_sram_data->SG_software_offset[SG_4];
            /* Timeslot++ */
            timeslot_number++;
            /* send data with radio if necessary */
            if (timeslot_number >= SAMPLES_PER_PACKET)
            {
                timeslot_number = 0;
                send_all_data_rf231();
            }
            /* Reset watchdog */
            wdt_reset();
        }
#if defined(USE_DS620)
        // Temperaturmessung staren wenn 200ms vorbei und DMS gerade nicht messen und nicht gesendet wird.
        if( (temperature_timer >= (eeprom_sram_data.samplerate / 9)) & (timeslot_number == 3))
        {
                    temperature = ds620_get_temperature();
                    temperature_timer = 0;
        }
#endif
    } // end for()
    return (0);
}
static void send_all_data_rf231 (void) [inline, static]
sendet ein Datenpacket
void set_sleep (void)
Routine zum Eintritt in den Standby-Modus.
Definition at line 499 of file WEPO41104A00.c.
References at86rf231_sleep(), besch_start_flag, device_all, ds620_sleep(), and SX8723c_sleep().
{
    cli();
    TCCR1B = 0x00; // Timer stoppen
    TIFR1 = 0x02; // Output Compare A Match Flag reset
    // SX8723c and strain gauges off
    SX8723c_sleep(device_all);
#if defined(USE_DS620)
    ds620_sleep(); // Temperatursensor stoppen
#endif
    ADCSRA = 0x00; // ADC off
    at86rf231_sleep(); // Transceiver in Power-down
    CLKPR = 0x80;
    CLKPR = 0x03; //08         // Prescaler 8
    PRR0 = 0xFE;
    if (besch_start_flag)
    {
        ACSR = 0x1A; // analog-Komperator an, Interrupt bei fallender Flanke
        set_sleep_mode(SLEEP_MODE_IDLE);
    }
    else
    {
        set_sleep_mode(SLEEP_MODE_PWR_SAVE);
    }
    wdt_reset();        //ank
    sleep_enable();
    sei();
    sleep_cpu(); // IDLE-Modus
    sleep_disable();
}
void start (void)
Startroutine zum Verlassen des Standby-Modus.
Parameters:
aos wenn AUTOOFFSET gesetzt ist: 0: kein Offsetabgleich, sonst Offsetabgeich ausführen
Definition at line 462 of file WEPO41104A00.c.
References besch_start_flag, device_all, ds620_init(), init_adc(), SX8723c_start(), timeout_timer, and timeslot_number.
Referenced by ISR(), and main().
{
    cli();
    PRR0 = 0x00;        // power manager: enable all modules
    /* Set system clock prescaler */
    CLKPR = 0x80;
    CLKPR = 0x00; // prescaler to 1
    if (besch_start_flag)
    {
        ACSR = 0x12; // analog-Komperator an, Interrupt aus
    }
    /* adc init */
    init_adc();
#if defined(USE_DS620)
    /* init temperature sensor */
    ds620_init();
#endif
    SX8723c_start(device_all);
    // reset time_slot to avoid sending old data; ank
    timeslot_number = 0;
    timeout_timer = 0;
    // start timer
    TCCR1B = 0x09; // CTC, no prescaling
    TIFR1 = 0x02;       // clear output compare a match flag
    sei();
}
void timer_init (void)
Initialisiert den Timer1 auf Interrupt im Intervall der Samplerate.
Definition at line 383 of file WEPO41104A00.c.
References eeprom_sram_data, F_CPU, and eeprom_data::samplerate.
Referenced by avr_init(), and pm_config_protocol().
{
    TCCR1A = 0x00; // CTC (clear timer on compare)
    TCCR1B = 0x09; // CTC, no prescaling
    OCR1A = (unsigned short) ((float) F_CPU
            / (float) eeprom_sram_data.samplerate); // Timer auf Samplerate einstellen
    TCNT1 = 0x0000;
    OCR1B = 0x0000;
    ICR1 = 0x0000;
    TIMSK1 = 1 << OCIE1A; // Timer1 Output Compare A Match, interrupt enable
    TIFR1 = 0x02;       // clear output compare a match flag
}